$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine("// <auto-generated />")
[void]$csharp.AppendLine("// Generated from Godswar Origin MonsterConfig.ini, Monster.ini files, QuestMonster.dat, and Quest.xml.")
[void]$csharp.AppendLine("namespace Godswar.Server.State;")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct MonsterTemplateSeed(string SourceKey, string SourceKind, short? SourceMapId, string SceneKey, string TemplateKey, string DisplayName, string Rank, bool IsBoss, bool IsElite, bool IsPet, short? AttackType, string ModelFile, string TextureFile, float? Scale, float? CollisionRange, float? NameHeight, string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct QuestMonsterReferenceSeed(int QuestId, string MonsterName, short? MapId, float? X, float? Z, int? MinLevel, int? MaxLevel, short? Faction, short? PetGroup, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal static class MonsterTemplateSeeds")
[void]$csharp.AppendLine("{")
[void]$csharp.AppendLine("    public static IReadOnlyList<MonsterTemplateSeed> Monsters { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $monsters) {
    $isBoss = if ($row.IsBoss) { "true" } else { "false" }
    $isElite = if ($row.IsElite) { "true" } else { "false" }
    $isPet = if ($row.IsPet) { "true" } else { "false" }
    [void]$csharp.AppendLine("        new($(ConvertTo-CSharpString $row.SourceKey), $(ConvertTo-CSharpString $row.SourceKind), $(ConvertTo-CSharpNullableShort $row.SourceMapId), $(ConvertTo-CSharpString $row.SceneKey), $(ConvertTo-CSharpString $row.TemplateKey), $(ConvertTo-CSharpString $row.DisplayName), $(ConvertTo-CSharpString $row.Rank), $isBoss, $isElite, $isPet, $(ConvertTo-CSharpNullableShort $row.AttackType), $(ConvertTo-CSharpString $row.ModelFile), $(ConvertTo-CSharpString $row.TextureFile), $(ConvertTo-CSharpNullableFloat $row.Scale), $(ConvertTo-CSharpNullableFloat $row.CollisionRange), $(ConvertTo-CSharpNullableFloat $row.NameHeight), $(ConvertTo-CSharpString $row.StatsJson)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<QuestMonsterReferenceSeed> QuestReferences { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $questMonsterReferences) {
    [void]$csharp.AppendLine("        new($($row.QuestId), $(ConvertTo-CSharpString $row.MonsterName), $(ConvertTo-CSharpNullableShort $row.MapId), $(ConvertTo-CSharpNullableFloat $row.X), $(ConvertTo-CSharpNullableFloat $row.Z), $(ConvertTo-CSharpNullableInt $row.MinLevel), $(ConvertTo-CSharpNullableInt $row.MaxLevel), $(ConvertTo-CSharpNullableShort $row.Faction), $(ConvertTo-CSharpNullableShort $row.PetGroup), $(ConvertTo-CSharpString $row.Source)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine("}")
