// <auto-generated />
// Generated by tools/GenerateClassSuitItemCatalog.ps1.
// ItemBaseAttribute.xml SHA256: 92984F8C9461B632CDEF02653929BDC2CB27D9F430DC528DC88F876BAF01F9D0
// EquipDescription.dat SHA256: 544B3A85DF45FF2ECD8E296B1F4279410666A9CF6F21C88704E73E625A612A26
// Canonical ascending item IDs SHA256: 3A8202C4021C0486DEB30F0D7A9BECA72F632E01227DDF2F1B0F6BFC9434B47D

namespace Godswar.Server.State;

internal static class ClassSuitItemCatalog
{
    public const int ShippedItemCount = 248;
    public const string CanonicalItemIdSha256 = "3A8202C4021C0486DEB30F0D7A9BECA72F632E01227DDF2F1B0F6BFC9434B47D";

    private static readonly uint[] ItemIds =
    [
        1032u, 1033u, 1034u, 1035u, 1432u, 1433u, 1434u, 1435u,
        1732u, 1733u, 1734u, 1735u, 1832u, 1833u, 1834u, 1835u,
        2031u, 2032u, 2033u, 2034u, 2041u, 2042u, 2043u, 2044u,
        2131u, 2132u, 2133u, 2134u, 2141u, 2142u, 2143u, 2144u,
        2151u, 2152u, 2153u, 2154u, 2161u, 2162u, 2163u, 2164u,
        2231u, 2232u, 2233u, 2234u, 2241u, 2242u, 2243u, 2244u,
        2251u, 2252u, 2253u, 2254u, 2261u, 2262u, 2263u, 2264u,
        2331u, 2332u, 2333u, 2334u, 2341u, 2342u, 2343u, 2344u,
        2431u, 2432u, 2433u, 2434u, 2441u, 2442u, 2443u, 2444u,
        2531u, 2532u, 2533u, 2534u, 2541u, 2542u, 2543u, 2544u,
        2551u, 2552u, 2553u, 2554u, 2561u, 2562u, 2563u, 2564u,
        2631u, 2632u, 2633u, 2634u, 2641u, 2642u, 2643u, 2644u,
        2651u, 2652u, 2653u, 2654u, 2661u, 2662u, 2663u, 2664u,
        2731u, 2732u, 2733u, 2734u, 2741u, 2742u, 2743u, 2744u,
        2751u, 2752u, 2753u, 2754u, 2761u, 2762u, 2763u, 2764u,
        2831u, 2832u, 2833u, 2834u, 2841u, 2842u, 2843u, 2844u,
        2851u, 2852u, 2853u, 2854u, 2861u, 2862u, 2863u, 2864u,
        2931u, 2932u, 2933u, 2934u, 2941u, 2942u, 2943u, 2944u,
        2951u, 2952u, 2953u, 2954u, 2961u, 2962u, 2963u, 2964u,
        3031u, 3032u, 3033u, 3034u, 3041u, 3042u, 3043u, 3044u,
        3051u, 3052u, 3053u, 3054u, 3061u, 3062u, 3063u, 3064u,
        3131u, 3132u, 3133u, 3134u, 3141u, 3142u, 3143u, 3144u,
        3151u, 3152u, 3153u, 3154u, 3161u, 3162u, 3163u, 3164u,
        3230u, 3231u, 3232u, 3233u, 3234u, 3235u, 3236u, 3237u,
        3240u, 3241u, 3242u, 3243u, 3244u, 3245u, 3246u, 3247u,
        3250u, 3251u, 3252u, 3253u, 3254u, 3255u, 3256u, 3257u,
        3260u, 3261u, 3262u, 3263u, 3264u, 3265u, 3266u, 3267u,
        3331u, 3332u, 3333u, 3334u, 3341u, 3342u, 3343u, 3344u,
        3351u, 3352u, 3353u, 3354u, 3361u, 3362u, 3363u, 3364u,
        3431u, 3432u, 3433u, 3434u, 3441u, 3442u, 3443u, 3444u,
        3451u, 3452u, 3453u, 3454u, 3461u, 3462u, 3463u, 3464u,
    ];

    public static IReadOnlyList<uint> AllItemIds { get; } = Array.AsReadOnly(ItemIds);

    public static bool IsClassSuit(uint itemId)
    {
        return Array.BinarySearch(ItemIds, itemId) >= 0;
    }
}
