// <auto-generated />
// Generated from Godswar Origin Skill.ini, Magic.ini, ItemBaseAttribute.xml, EquipName.dat, and SkillInfo.dat.
namespace Godswar.Server.State;

internal readonly record struct ClassTemplateSeed(short Id, string Name, string DisplayName, string Source);

internal readonly record struct TalentEffectTemplateSeed(short Id, string Key, string DisplayName, bool Percent);

internal readonly record struct TalentTemplateSeed(
    int Id,
    short ClassId,
    short TreeOrder,
    string Name,
    int PrefixId,
    int RequiredPrefixRank,
    int RequiredTotalRank,
    int EquipRequest,
    string EffectType,
    short EffectId,
    decimal EffectValue,
    bool IsPercent,
    int IconX,
    int IconY,
    int IconWidth,
    int IconHeight,
    string StatsJson);

internal readonly record struct SkillTemplateSeed(
    int SkillId,
    string DisplayName,
    string BaseName,
    short? SkillLevel,
    short[] ClassIds,
    int? PreviousSkillId,
    int? MinLevel,
    int? MaxLevel,
    string Description,
    int Target,
    int AffectObj,
    decimal Distance,
    decimal Range,
    int Property,
    int Mp,
    decimal Power1,
    decimal Power2,
    decimal IntonateTime,
    decimal CoolingTime,
    string StatsJson);

internal readonly record struct SkillBookTemplateSeed(
    int ItemId,
    string NameKey,
    string DisplayName,
    int SkillId,
    string BaseName,
    short? SkillLevel,
    short[] ClassIds,
    int? MinLevel,
    int? MaxLevel,
    int? PreviousSkillId,
    string StatsJson);

internal static partial class SkillTalentSeeds
{
    public static IReadOnlyList<ClassTemplateSeed> Classes { get; } =
    [
        .. CreateClassesChunk000(),
    ];

    public static IReadOnlyList<TalentEffectTemplateSeed> TalentEffects { get; } =
    [
        .. CreateTalentEffectsChunk000(),
    ];

    public static IReadOnlyList<TalentTemplateSeed> Talents { get; } =
    [
        .. CreateTalentsChunk000(),
        .. CreateTalentsChunk001(),
    ];

    public static IReadOnlyList<SkillTemplateSeed> Skills { get; } =
    [
        .. CreateSkillsChunk000(),
        .. CreateSkillsChunk001(),
        .. CreateSkillsChunk002(),
        .. CreateSkillsChunk003(),
        .. CreateSkillsChunk004(),
        .. CreateSkillsChunk005(),
        .. CreateSkillsChunk006(),
        .. CreateSkillsChunk007(),
    ];

    public static IReadOnlyList<SkillBookTemplateSeed> SkillBooks { get; } =
    [
        .. CreateSkillBooksChunk000(),
        .. CreateSkillBooksChunk001(),
        .. CreateSkillBooksChunk002(),
        .. CreateSkillBooksChunk003(),
        .. CreateSkillBooksChunk004(),
        .. CreateSkillBooksChunk005(),
        .. CreateSkillBooksChunk006(),
    ];

}
