// <auto-generated skill-talent-seed chunk />
// Generated from Godswar Origin Skill.ini, Magic.ini, ItemBaseAttribute.xml, EquipName.dat, and SkillInfo.dat.
namespace Godswar.Server.State;

internal static partial class SkillTalentSeeds
{
    private static ClassTemplateSeed[] CreateClassesChunk000() =>
    [
        new(0, "warrior", "Warrior", "Skill.ini class0 / Message.dat Warriorbuild"),
        new(1, "champion", "Champion", "Skill.ini class1 / Message.dat Spearmanbuild"),
        new(2, "priest", "Priest", "Skill.ini class2 / Message.dat Flamenbuild"),
        new(3, "mage", "Mage", "Skill.ini class3 / Message.dat Magebuild"),
    ];
}
