// <auto-generated skill-talent-seed chunk />
// Generated from Godswar Origin Skill.ini, Magic.ini, ItemBaseAttribute.xml, EquipName.dat, and SkillInfo.dat.
namespace Godswar.Server.State;

internal static partial class SkillTalentSeeds
{
    private static TalentEffectTemplateSeed[] CreateTalentEffectsChunk000() =>
    [
        new(0, "MaxHP", "Maximum Health+", false),
        new(1, "MaxMP", "Maximum Mana+", false),
        new(2, "Hit", "Hit Rating+", false),
        new(3, "Miss", "Dodge Rating+", false),
        new(4, "PhyAttack", "Melee Damage+", false),
        new(5, "PhyDefend", "Melee Defense+", false),
        new(6, "MagicAttack", "Magical Damage+", false),
        new(7, "MagicDefend", "Magical Defense+", false),
        new(8, "FrenzyHit", "Crit+", false),
        new(9, "FrenzyMiss", "Crit Resistance+", false),
        new(10, "DamageSorb", "Damage Absorption+", false),
        new(11, "PhyDamage", "Melee Damage+", true),
        new(12, "MagicDamage", "Magical Damage+", true),
        new(13, "HPResume", "HP Restoration Spd+", false),
        new(14, "MPResume", "MP Restoration Spd+", false),
        new(15, "StatusHit", "Duration Based Spell Hit Rating+", false),
        new(16, "StatusMiss", "Duration Based Spell Resistance Rating+", false),
        new(17, "Cure", "Healing effects+", true),
        new(18, "Becure", "Effects of healing done+", true),
    ];
}
