using System.Security.Cryptography;
using System.Text;
using Godswar.Server.State;

namespace Godswar.Server.ProtocolChecks;

internal static partial class PostgresMigrationFoundationChecks
{
    private static async Task CheckBootstrapResourceIdentityAsync()
    {
        const int expectedByteCount = 91_130;
        const string expectedSha256 =
            "89A0954633CD65DE8AB9C72D74CFE65F651D24171DE60071102B3958B848C7C7";
        var strictUtf8 = new UTF8Encoding(
            encoderShouldEmitUTF8Identifier: false,
            throwOnInvalidBytes: true);
        var sql = await LegacySchemaBootstrap.LoadAsync(CancellationToken.None);
        var bytes = strictUtf8.GetBytes(sql);

        Check.Equal(expectedByteCount, bytes.Length, "legacy bootstrap byte count");
        Check.Equal(
            expectedSha256,
            Convert.ToHexString(SHA256.HashData(bytes)),
            "legacy bootstrap fragment reconstruction hash");
        Check.True(
            sql.Contains(
                "CREATE TABLE IF NOT EXISTS public.packet_capture_sessions",
                StringComparison.Ordinal) &&
            sql.Contains(
                "CREATE TABLE IF NOT EXISTS public.packet_transactions",
                StringComparison.Ordinal) &&
            sql.Contains(
                "CREATE TABLE IF NOT EXISTS public.packet_opcodes",
                StringComparison.Ordinal) &&
            sql.Contains(
                "CREATE OR REPLACE FUNCTION public.set_packet_transaction_opcode_name()",
                StringComparison.Ordinal) &&
            sql.Contains(
                "GENERATED BY DEFAULT AS IDENTITY",
                StringComparison.Ordinal) &&
            sql.Contains(
                "REFERENCES public.packet_capture_sessions (id) ON DELETE CASCADE",
                StringComparison.Ordinal) &&
            sql.Contains(
                "CHECK (direction IN ('ANY', 'C2S', 'S2C'))",
                StringComparison.Ordinal) &&
            sql.Contains(
                "CREATE TRIGGER trg_packet_transactions_opcode_name",
                StringComparison.Ordinal),
            "fresh-database bootstrap owns every packet-metadata prerequisite");
    }
}
