CREATE TABLE IF NOT EXISTS accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL DEFAULT '',
    email varchar(255) NOT NULL DEFAULT '',
    username varchar(32) NOT NULL,
    password varchar(255) NOT NULL DEFAULT '',
    login_status smallint NOT NULL DEFAULT 0,
    last_login_time timestamptz NOT NULL DEFAULT now(),
    last_logout_time timestamptz NOT NULL DEFAULT now(),
    last_login_ip varchar(255) NOT NULL DEFAULT '',
    last_login_mac varchar(255) NOT NULL DEFAULT '',
    total_online_time bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_accounts_username ON accounts (username);

CREATE TABLE IF NOT EXISTS server (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    identifier varchar(25) NOT NULL,
    ip_address varchar(255) NOT NULL,
    server_limit integer NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_server_identifier ON server (identifier);

INSERT INTO server (id, name, identifier, ip_address, server_limit)
VALUES (1, 'Tempest', 'KAL3jcIzqGgKvOf1dbYZKC8cS', '127.1.1.110', 250)
ON CONFLICT (identifier) DO UPDATE
SET name = EXCLUDED.name,
    ip_address = EXCLUDED.ip_address,
    server_limit = EXCLUDED.server_limit;

CREATE TABLE IF NOT EXISTS item_templates (
    id integer PRIMARY KEY,
    kind varchar(32) NOT NULL,
    name_key varchar(128) NOT NULL,
    display_name varchar(255) NOT NULL,
    equipment_slot smallint NOT NULL,
    class_ids smallint[] NOT NULL DEFAULT '{}',
    min_level integer,
    max_level integer,
    hand smallint,
    skill_flag integer,
    texture varchar(255) NOT NULL DEFAULT '',
    icon varchar(32) NOT NULL DEFAULT '',
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_item_templates_kind ON item_templates (kind);
CREATE INDEX IF NOT EXISTS ix_item_templates_equipment_slot ON item_templates (equipment_slot);
CREATE INDEX IF NOT EXISTS ix_item_templates_class_ids ON item_templates USING gin (class_ids);

CREATE TABLE IF NOT EXISTS item_quality_levels (
    level smallint PRIMARY KEY,
    name varchar(32) NOT NULL,
    color varchar(64) NOT NULL
);

INSERT INTO item_quality_levels (level, name, color)
VALUES
    (1, 'Common', 'DEFAULT_TEXTCOLOR'),
    (2, 'Enhanced', 'TEAM_COLOR'),
    (3, 'Delicate', 'ItemCOLOR'),
    (4, 'Good', 'GREEN_TEXTCOLOR'),
    (5, 'Superior', 'GUILD_COLOR'),
    (6, 'Classic', 'Classical_color'),
    (7, 'Eternal', 'YELLOW_TEXTCOLOR'),
    (8, 'Epic', 'WHISPER_COLOR'),
    (9, 'Legendary', 'Legend_color'),
    (10, 'Mystic', 'Itemper_color'),
    (11, 'Divine', 'Divine_color'),
    (12, 'Celestial', 'Celestial_color'),
    (13, 'Mythical', 'Mythical_color'),
    (14, 'Astral', 'Astral_color'),
    (15, 'Arcane', 'Arcane_color'),
    (16, 'Ethereal', 'Ethereal_color'),
    (17, 'Transcendent', 'Transcendent_color'),
    (18, 'Ancient', 'Ancient_color'),
    (19, 'Primordial', 'Primordial_color'),
    (20, 'Boundless', 'Boundless_color')
ON CONFLICT (level) DO UPDATE
SET name = EXCLUDED.name,
    color = EXCLUDED.color;

CREATE TABLE IF NOT EXISTS item_grade_levels (
    level smallint PRIMARY KEY,
    stars smallint NOT NULL,
    color varchar(64) NOT NULL,
    attribute_color varchar(64) NOT NULL
);

INSERT INTO item_grade_levels (level, stars, color, attribute_color)
VALUES
    (1, 1, 'DEFAULT_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (2, 2, 'DEFAULT_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (3, 3, 'TEAM_COLOR', 'GREEN_TEXTCOLOR'),
    (4, 4, 'TEAM_COLOR', 'GREEN_TEXTCOLOR'),
    (5, 5, 'ItemCOLOR', 'GREEN_TEXTCOLOR'),
    (6, 6, 'GREEN_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (7, 7, 'GUILD_COLOR', 'GREEN_TEXTCOLOR'),
    (8, 8, 'YELLOW_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (9, 9, 'WHISPER_COLOR', 'GREEN_TEXTCOLOR'),
    (10, 10, 'WHISPER_COLOR', 'GREEN_TEXTCOLOR'),
    (11, 11, 'Legend_color', 'GREEN_TEXTCOLOR'),
    (12, 12, 'Itemper_color', 'GREEN_TEXTCOLOR'),
    (13, 13, 'Divine_color', 'GREEN_TEXTCOLOR'),
    (14, 14, 'Divine_color', 'GREEN_TEXTCOLOR'),
    (15, 15, 'Celestial_color', 'GREEN_TEXTCOLOR'),
    (16, 16, 'Celestial_color', 'GREEN_TEXTCOLOR'),
    (17, 17, 'Mythical_color', 'GREEN_TEXTCOLOR'),
    (18, 18, 'Mythical_color', 'GREEN_TEXTCOLOR'),
    (19, 19, 'Astral_color', 'GREEN_TEXTCOLOR'),
    (20, 20, 'Arcane_color', 'GREEN_TEXTCOLOR'),
    (21, 21, 'Transcendent_color', 'GREEN_TEXTCOLOR'),
    (22, 22, 'Ancient_color', 'GREEN_TEXTCOLOR'),
    (23, 23, 'Primordial_color', 'GREEN_TEXTCOLOR'),
    (24, 24, 'Primordial_color', 'GREEN_TEXTCOLOR'),
    (25, 25, 'Boundless_color', 'GREEN_TEXTCOLOR')
ON CONFLICT (level) DO UPDATE
SET stars = EXCLUDED.stars,
    color = EXCLUDED.color,
    attribute_color = EXCLUDED.attribute_color;

CREATE TABLE IF NOT EXISTS equipment_rank_rules (
    rank_kind varchar(16) NOT NULL,
    rank_level smallint NOT NULL,
    required_score integer NOT NULL,
    aura_effect integer NOT NULL,
    source varchar(64) NOT NULL,
    PRIMARY KEY (rank_kind, rank_level)
);

INSERT INTO equipment_rank_rules (rank_kind, rank_level, required_score, aura_effect, source)
VALUES
    ('weapon', 1, 40, 1, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 2, 100, 2, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 3, 180, 3, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 4, 240, 4, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 5, 300, 5, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 6, 460, 5, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 7, 600, 5, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 8, 1200, 6, 'extended_ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 9, 4000, 8, 'extended_ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 10, 8000, 9, 'extended_ItemBaseAttribute.ArmEffFraction'),
    ('armor', 1, 330, 1, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 2, 475, 2, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 3, 750, 3, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 4, 950, 4, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 5, 1350, 5, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 6, 1720, 6, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 7, 2225, 7, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 8, 3860, 8, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 9, 5250, 9, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 10, 8000, 10, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 11, 12000, 11, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 12, 17000, 12, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 13, 22000, 13, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 14, 25300, 14, 'extended_ItemBaseAttribute.DefendFraction')
ON CONFLICT (rank_kind, rank_level) DO UPDATE
SET required_score = EXCLUDED.required_score,
    aura_effect = EXCLUDED.aura_effect,
    source = EXCLUDED.source;

DELETE FROM equipment_rank_rules
WHERE rank_kind = 'armor'
  AND rank_level > 14;

CREATE TABLE IF NOT EXISTS character_base (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    server_id integer REFERENCES server(id),
    name varchar(32) NOT NULL,
    gender varchar(6) NOT NULL DEFAULT 'male' CHECK (gender IN ('female', 'male')),
    "GM" smallint NOT NULL DEFAULT 0,
    camp smallint NOT NULL DEFAULT 1,
    profession smallint NOT NULL DEFAULT 0,
    fighter_job_lv integer NOT NULL DEFAULT 1,
    scholar_job_lv integer NOT NULL DEFAULT 0,
    fighter_job_exp integer NOT NULL DEFAULT 0,
    scholar_job_exp integer NOT NULL DEFAULT 0,
    "curHP" integer NOT NULL DEFAULT 1500,
    "curMP" integer NOT NULL DEFAULT 177,
    vitals_revision bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0,
    belief smallint NOT NULL DEFAULT 1,
    prestige integer NOT NULL DEFAULT 0,
    earl_rank smallint NOT NULL DEFAULT 0,
    consortia integer NOT NULL DEFAULT 0,
    consortia_job smallint NOT NULL DEFAULT 0,
    consortia_contribute integer NOT NULL DEFAULT 0,
    store_num integer NOT NULL DEFAULT 10,
    bag_num integer NOT NULL DEFAULT 1,
    hair_style smallint NOT NULL DEFAULT 0,
    face_shap smallint DEFAULT 0,
    "Map" smallint NOT NULL DEFAULT 1,
    "Pos_X" real NOT NULL DEFAULT 165.0,
    "Pos_Z" real NOT NULL DEFAULT -97.0,
    "Money" integer NOT NULL DEFAULT 10000,
    "Stone" integer NOT NULL DEFAULT 10,
    "SkillPoint" integer NOT NULL DEFAULT 10,
    "SkillExp" integer NOT NULL DEFAULT 0,
    holy_suit_points integer NOT NULL DEFAULT 0,
    "MaxHP" integer NOT NULL DEFAULT 1500,
    "MaxMP" integer NOT NULL DEFAULT 177,
    "Register_time" timestamptz NOT NULL DEFAULT now(),
    "LastLogin_time" timestamptz NOT NULL DEFAULT now(),
    mutetime integer DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_character_base_name ON character_base (name);
CREATE INDEX IF NOT EXISTS ix_character_base_account ON character_base (account_id);
CREATE INDEX IF NOT EXISTS ix_character_base_server ON character_base (server_id);
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS holy_suit_points integer NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS vitals_revision bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS character_kitbag (
    user_id integer PRIMARY KEY REFERENCES character_base(id) ON DELETE CASCADE,
    kitbag_1 varchar(4000),
    kitbag_2 varchar(4000),
    kitbag_3 varchar(4000),
    kitbag_4 varchar(4000),
    storage varchar(4000),
    equip varchar(2000)
);

CREATE TABLE IF NOT EXISTS character_equip (
    user_id integer NOT NULL REFERENCES character_base(id) ON DELETE CASCADE,
    body_part_id smallint NOT NULL,
    prop_id integer NOT NULL,
    type1 smallint,
    quality1 smallint,
    value1 real,
    type2 smallint,
    quality2 smallint,
    value2 real,
    type3 smallint,
    quality3 smallint,
    value3 real,
    type4 smallint,
    quality4 smallint,
    value4 real,
    type5 smallint,
    quality5 smallint,
    value5 real,
    item_quality smallint NOT NULL DEFAULT 1,
    item_grade smallint NOT NULL DEFAULT 1,
    bound smallint NOT NULL DEFAULT 1,
    stack smallint NOT NULL DEFAULT 1,
    item_exp integer NOT NULL DEFAULT 0,
    holy_suit_type smallint NOT NULL DEFAULT 0,
    holy_suit_level smallint NOT NULL DEFAULT 0,
    holy_suit_code integer NOT NULL DEFAULT 0,
    isbind smallint DEFAULT 0,
    PRIMARY KEY (user_id, body_part_id)
);

ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS item_quality smallint NOT NULL DEFAULT 1;
ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS item_grade smallint NOT NULL DEFAULT 1;
ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS bound smallint NOT NULL DEFAULT 1;
ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS stack smallint NOT NULL DEFAULT 1;
ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS item_exp integer NOT NULL DEFAULT 0;
ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS holy_suit_type smallint NOT NULL DEFAULT 0;
ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS holy_suit_level smallint NOT NULL DEFAULT 0;
ALTER TABLE character_equip ADD COLUMN IF NOT EXISTS holy_suit_code integer NOT NULL DEFAULT 0;

CREATE OR REPLACE VIEW character_equipment_scores AS
WITH score_parts AS (
    SELECT
        ce.user_id,
        ce.body_part_id,
        ce.prop_id,
        ce.item_quality,
        ce.item_grade,
        ce.bound,
        ce.stack,
        ce.item_exp,
        ce.holy_suit_type,
        ce.holy_suit_level,
        ce.holy_suit_code,
        it.kind,
        it.display_name,
        it.equipment_slot,
        (
            (ce.type1 IS NOT NULL AND ce.type1 >= 0)::integer +
            (ce.type2 IS NOT NULL AND ce.type2 >= 0)::integer +
            (ce.type3 IS NOT NULL AND ce.type3 >= 0)::integer +
            (ce.type4 IS NOT NULL AND ce.type4 >= 0)::integer +
            (ce.type5 IS NOT NULL AND ce.type5 >= 0)::integer
        ) AS append_attribute_count,
        CASE
            WHEN base_values.values IS NULL THEN 0
            ELSE COALESCE(NULLIF(base_values.values[
                LEAST(GREATEST(ce.item_quality::integer, 1), array_length(base_values.values, 1))
            ], '')::integer, 0)
        END AS base_score,
        CASE
            WHEN app_values.values IS NULL THEN 0
            ELSE COALESCE(NULLIF(app_values.values[
                LEAST(GREATEST(ce.item_grade::integer, 1), array_length(app_values.values, 1))
            ], '')::integer, 0)
        END AS grade_score
    FROM character_equip ce
    LEFT JOIN item_templates it ON it.id = ce.prop_id
    LEFT JOIN LATERAL (
        SELECT string_to_array(it.stats->>'BaseFraction', ',') AS values
        WHERE it.stats ? 'BaseFraction'
    ) base_values ON true
    LEFT JOIN LATERAL (
        SELECT string_to_array(it.stats->>'AppFraction', ',') AS values
        WHERE it.stats ? 'AppFraction'
    ) app_values ON true
)
SELECT
    user_id,
    body_part_id,
    prop_id,
    kind,
    display_name,
    equipment_slot,
    item_quality,
    item_grade,
    bound,
    stack,
    item_exp,
    base_score,
    grade_score * append_attribute_count AS grade_score,
    base_score + (grade_score * append_attribute_count) AS item_score,
    holy_suit_type,
    holy_suit_level,
    holy_suit_code
FROM score_parts;

CREATE OR REPLACE VIEW character_rank_summary AS
WITH totals AS (
    SELECT
        user_id,
        COALESCE(SUM(item_score) FILTER (WHERE kind = 'weapon'), 0)::integer AS weapon_score,
        COALESCE(SUM(item_score) FILTER (WHERE kind <> 'weapon'), 0)::integer AS armor_score
    FROM character_equipment_scores
    GROUP BY user_id
)
SELECT
    cb.id AS user_id,
    cb.name,
    COALESCE(t.weapon_score, 0) AS weapon_score,
    COALESCE(wr.rank_level, 0)::smallint AS weapon_rank,
    COALESCE(wr.aura_effect, 0) AS weapon_aura_effect,
    COALESCE(t.armor_score, 0) AS armor_score,
    COALESCE(ar.rank_level, 0)::smallint AS armor_rank,
    COALESCE(ar.aura_effect, 0) AS armor_aura_effect
FROM character_base cb
LEFT JOIN totals t ON t.user_id = cb.id
LEFT JOIN LATERAL (
    SELECT rank_level, aura_effect
    FROM equipment_rank_rules
    WHERE rank_kind = 'weapon'
      AND required_score <= COALESCE(t.weapon_score, 0)
    ORDER BY rank_level DESC
    LIMIT 1
) wr ON true
LEFT JOIN LATERAL (
    SELECT rank_level, aura_effect
    FROM equipment_rank_rules
    WHERE rank_kind = 'armor'
      AND required_score <= COALESCE(t.armor_score, 0)
    ORDER BY rank_level DESC
    LIMIT 1
) ar ON true;
