CREATE TABLE IF NOT EXISTS packet_capture_sessions (
    id uuid PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    capture_name varchar(128) NOT NULL DEFAULT '',
    login_host varchar(255) NOT NULL DEFAULT '',
    login_port integer NOT NULL DEFAULT 0,
    local_login_port integer NOT NULL DEFAULT 0,
    local_game_port integer NOT NULL DEFAULT 0,
    local_advertised_host varchar(255) NOT NULL DEFAULT '',
    default_game_host varchar(255),
    default_game_port integer NOT NULL DEFAULT 0,
    output_path text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS packet_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capture_session_id uuid NOT NULL REFERENCES packet_capture_sessions (id) ON DELETE CASCADE,
    captured_at timestamptz NOT NULL DEFAULT now(),
    connection_id uuid NOT NULL,
    connection_name varchar(16) NOT NULL,
    direction varchar(4) NOT NULL,
    source_endpoint varchar(128) NOT NULL DEFAULT '',
    destination_endpoint varchar(128) NOT NULL DEFAULT '',
    chunk_sequence bigint NOT NULL,
    packet_sequence bigint NOT NULL,
    packet_index integer NOT NULL,
    stream_offset bigint NOT NULL,
    declared_length integer,
    actual_length integer NOT NULL,
    opcode integer,
    clear_bytes bytea NOT NULL,
    raw_bytes bytea NOT NULL,
    notes text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_session_sequence
    ON packet_transactions (capture_session_id, packet_sequence);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_opcode
    ON packet_transactions (opcode);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_direction
    ON packet_transactions (connection_name, direction);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_captured_at
    ON packet_transactions (captured_at);
