CREATE TABLE IF NOT EXISTS character_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES character_base(id) ON DELETE CASCADE,
    item_location smallint NOT NULL,
    slot_index smallint NOT NULL,
    prop_id integer NOT NULL,
    attribute1 smallint,
    attribute2 smallint,
    attribute3 smallint,
    attribute4 smallint,
    attribute5 smallint,
    attribute_level1 smallint,
    attribute_level2 smallint,
    attribute_level3 smallint,
    attribute_level4 smallint,
    attribute_level5 smallint,
    item_quality smallint NOT NULL DEFAULT 1,
    item_grade smallint NOT NULL DEFAULT 1,
    bound smallint NOT NULL DEFAULT 1,
    stack smallint NOT NULL DEFAULT 1,
    item_exp integer NOT NULL DEFAULT 0,
    holy_suit_code integer NOT NULL DEFAULT 0,
    holy_socket_count smallint NOT NULL DEFAULT 0,
    holy_socket1_effect_id smallint,
    holy_socket1_level smallint,
    holy_socket2_effect_id smallint,
    holy_socket2_level smallint,
    holy_socket3_effect_id smallint,
    holy_socket3_level smallint,
    holy_socket4_effect_id smallint,
    holy_socket4_level smallint,
    holy_socket5_effect_id smallint,
    holy_socket5_level smallint,
    holy_socket6_effect_id smallint,
    holy_socket6_level smallint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ux_character_items_location_slot UNIQUE (user_id, item_location, slot_index),
    CONSTRAINT ck_character_items_location CHECK (item_location IN (0, 1, 2))
);

CREATE INDEX IF NOT EXISTS ix_character_items_user_location
    ON character_items (user_id, item_location, slot_index);

ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket_count smallint NOT NULL DEFAULT 0;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket1_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket1_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket2_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket2_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket3_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket3_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket4_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket4_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket5_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket5_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket6_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket6_level smallint;

INSERT INTO character_items (
    user_id, item_location, slot_index, prop_id,
    attribute1, attribute2, attribute3, attribute4, attribute5,
    attribute_level1, attribute_level2, attribute_level3, attribute_level4, attribute_level5,
    item_quality, item_grade, bound, stack, item_exp, holy_suit_code
)
SELECT
    ce.user_id,
    0,
    ce.body_part_id,
    ce.prop_id,
    ce.type1,
    ce.type2,
    ce.type3,
    ce.type4,
    ce.type5,
    ce.quality1,
    ce.quality2,
    ce.quality3,
    ce.quality4,
    ce.quality5,
    ce.item_quality,
    ce.item_grade,
    ce.bound,
    ce.stack,
    ce.item_exp,
    ce.holy_suit_code
FROM character_equip ce
ON CONFLICT (user_id, item_location, slot_index) DO NOTHING;

WITH entries AS (
    SELECT
        ck.user_id,
        item.ordinality - 1 AS slot_index,
        string_to_array(trim(both '[]' FROM item.entry), ',') AS item_parts
    FROM character_kitbag ck
    CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ck.kitbag_1, ''), '#') WITH ORDINALITY AS item(entry, ordinality)
    WHERE item.entry <> ''
      AND item.entry <> '[]'
)
INSERT INTO character_items (
    user_id, item_location, slot_index, prop_id,
    attribute1, attribute2, attribute3, attribute4, attribute5,
    attribute_level1, attribute_level2, attribute_level3, attribute_level4, attribute_level5,
    item_quality, item_grade, bound, stack, item_exp, holy_suit_code,
    holy_socket_count, holy_socket1_effect_id, holy_socket1_level, holy_socket2_effect_id, holy_socket2_level,
    holy_socket3_effect_id, holy_socket3_level, holy_socket4_effect_id, holy_socket4_level,
    holy_socket5_effect_id, holy_socket5_level, holy_socket6_effect_id, holy_socket6_level
)
SELECT
    user_id,
    1,
    slot_index,
    NULLIF(item_parts[1], '')::integer,
    CASE WHEN NULLIF(item_parts[2], '') IS NOT NULL AND NULLIF(item_parts[2], '')::integer >= 0 THEN NULLIF(item_parts[2], '')::smallint END,
    CASE WHEN NULLIF(item_parts[3], '') IS NOT NULL AND NULLIF(item_parts[3], '')::integer >= 0 THEN NULLIF(item_parts[3], '')::smallint END,
    CASE WHEN NULLIF(item_parts[4], '') IS NOT NULL AND NULLIF(item_parts[4], '')::integer >= 0 THEN NULLIF(item_parts[4], '')::smallint END,
    CASE WHEN NULLIF(item_parts[5], '') IS NOT NULL AND NULLIF(item_parts[5], '')::integer >= 0 THEN NULLIF(item_parts[5], '')::smallint END,
    CASE WHEN NULLIF(item_parts[6], '') IS NOT NULL AND NULLIF(item_parts[6], '')::integer >= 0 THEN NULLIF(item_parts[6], '')::smallint END,
    NULLIF(item_parts[13], '')::smallint,
    NULLIF(item_parts[14], '')::smallint,
    NULLIF(item_parts[15], '')::smallint,
    NULLIF(item_parts[16], '')::smallint,
    NULLIF(item_parts[17], '')::smallint,
    COALESCE(NULLIF(item_parts[7], '')::smallint, 1),
    COALESCE(NULLIF(item_parts[8], '')::smallint, 1),
    COALESCE(NULLIF(item_parts[9], '')::smallint, 0),
    COALESCE(NULLIF(item_parts[10], '')::smallint, 1),
    COALESCE(NULLIF(item_parts[11], '')::integer, 0),
    COALESCE(NULLIF(item_parts[12], '')::integer, 0),
    COALESCE(NULLIF(item_parts[18], '')::smallint, 0),
    NULLIF(item_parts[19], '')::smallint,
    NULLIF(item_parts[20], '')::smallint,
    NULLIF(item_parts[21], '')::smallint,
    NULLIF(item_parts[22], '')::smallint,
    NULLIF(item_parts[23], '')::smallint,
    NULLIF(item_parts[24], '')::smallint,
    NULLIF(item_parts[25], '')::smallint,
    NULLIF(item_parts[26], '')::smallint,
    NULLIF(item_parts[27], '')::smallint,
    NULLIF(item_parts[28], '')::smallint,
    NULLIF(item_parts[29], '')::smallint,
    NULLIF(item_parts[30], '')::smallint
FROM entries
WHERE NULLIF(item_parts[1], '') IS NOT NULL
ON CONFLICT (user_id, item_location, slot_index) DO NOTHING;

CREATE OR REPLACE VIEW character_item_compact_entries AS
SELECT
    ci.user_id,
    ci.item_location,
    ci.slot_index,
    '[' ||
    ci.prop_id::text || ',' ||
    COALESCE(ci.attribute1::text, '') || ',' ||
    COALESCE(ci.attribute2::text, '') || ',' ||
    COALESCE(ci.attribute3::text, '') || ',' ||
    COALESCE(ci.attribute4::text, '') || ',' ||
    COALESCE(ci.attribute5::text, '') || ',' ||
    LEAST(GREATEST(ci.item_quality::integer, 1), COALESCE(quality_limits.base_levels, ci.item_quality::integer))::text || ',' ||
    LEAST(GREATEST(ci.item_grade::integer, 1), LEAST(COALESCE(quality_limits.grade_levels, ci.item_grade::integer), 25))::text || ',' ||
    ci.bound::text || ',' ||
    ci.stack::text || ',' ||
    ci.item_exp::text || ',' ||
    ci.holy_suit_code::text || ',' ||
    COALESCE(ci.attribute_level1::text, '') || ',' ||
    COALESCE(ci.attribute_level2::text, '') || ',' ||
    COALESCE(ci.attribute_level3::text, '') || ',' ||
    COALESCE(ci.attribute_level4::text, '') || ',' ||
    COALESCE(ci.attribute_level5::text, '') || ',' ||
    COALESCE(ci.holy_socket_count::text, '0') || ',' ||
    COALESCE(ci.holy_socket1_effect_id::text, '') || ',' ||
    COALESCE(ci.holy_socket1_level::text, '') || ',' ||
    COALESCE(ci.holy_socket2_effect_id::text, '') || ',' ||
    COALESCE(ci.holy_socket2_level::text, '') || ',' ||
    COALESCE(ci.holy_socket3_effect_id::text, '') || ',' ||
    COALESCE(ci.holy_socket3_level::text, '') || ',' ||
    COALESCE(ci.holy_socket4_effect_id::text, '') || ',' ||
    COALESCE(ci.holy_socket4_level::text, '') || ',' ||
    COALESCE(ci.holy_socket5_effect_id::text, '') || ',' ||
    COALESCE(ci.holy_socket5_level::text, '') || ',' ||
    COALESCE(ci.holy_socket6_effect_id::text, '') || ',' ||
    COALESCE(ci.holy_socket6_level::text, '') ||
    ']' AS compact_entry
FROM character_items ci
LEFT JOIN item_templates it ON it.id = ci.prop_id
LEFT JOIN LATERAL (
    SELECT
        NULLIF(array_length(string_to_array(NULLIF(it.stats->>'BaseFraction', ''), ','), 1), 0) AS base_levels,
        NULLIF(array_length(string_to_array(NULLIF(it.stats->>'AppFraction', ''), ','), 1), 0) AS grade_levels
) quality_limits ON true;

CREATE OR REPLACE VIEW character_item_validation AS
SELECT
    ci.user_id,
    ci.item_location,
    ci.slot_index,
    ci.prop_id,
    it.display_name,
    ci.item_quality AS requested_quality,
    COALESCE(quality_limits.base_levels, ci.item_quality::integer)::smallint AS max_packet_quality,
    LEAST(GREATEST(ci.item_quality::integer, 1), COALESCE(quality_limits.base_levels, ci.item_quality::integer))::smallint AS packet_quality,
    ci.item_grade AS requested_grade,
    LEAST(COALESCE(quality_limits.grade_levels, ci.item_grade::integer), 25)::smallint AS max_packet_grade,
    LEAST(GREATEST(ci.item_grade::integer, 1), LEAST(COALESCE(quality_limits.grade_levels, ci.item_grade::integer), 25))::smallint AS packet_grade,
    ci.item_quality > COALESCE(quality_limits.base_levels, ci.item_quality::integer) AS quality_exceeds_item_template,
    ci.item_grade > LEAST(COALESCE(quality_limits.grade_levels, ci.item_grade::integer), 25) AS grade_exceeds_item_template
FROM character_items ci
LEFT JOIN item_templates it ON it.id = ci.prop_id
LEFT JOIN LATERAL (
    SELECT
        NULLIF(array_length(string_to_array(NULLIF(it.stats->>'BaseFraction', ''), ','), 1), 0) AS base_levels,
        NULLIF(array_length(string_to_array(NULLIF(it.stats->>'AppFraction', ''), ','), 1), 0) AS grade_levels
) quality_limits ON true;

CREATE OR REPLACE VIEW character_item_loadout AS
SELECT
    cb.id AS user_id,
    COALESCE(equipment.equip, '') AS equip,
    COALESCE(kitbag.kitbag_1, '') AS kitbag_1
FROM character_base cb
LEFT JOIN LATERAL (
    SELECT string_agg(COALESCE(cice.compact_entry, '[]'), '#' ORDER BY slot.slot_index) || '#' AS equip
    FROM generate_series(0, 23) AS slot(slot_index)
    LEFT JOIN character_item_compact_entries cice
        ON cice.user_id = cb.id
       AND cice.item_location = 0
       AND cice.slot_index = slot.slot_index
) equipment ON true
LEFT JOIN LATERAL (
    SELECT string_agg(COALESCE(cice.compact_entry, '[]'), '#' ORDER BY slot.slot_index) || '#' AS kitbag_1
    FROM generate_series(0, 95) AS slot(slot_index)
    LEFT JOIN character_item_compact_entries cice
        ON cice.user_id = cb.id
       AND cice.item_location = 1
       AND cice.slot_index = slot.slot_index
) kitbag ON true;
