CREATE TABLE IF NOT EXISTS character_item_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at timestamptz NOT NULL DEFAULT now(),
    source varchar(64) NOT NULL,
    action varchar(32) NOT NULL,
    user_id integer NOT NULL,
    item_location smallint NOT NULL,
    slot_index smallint NOT NULL,
    prop_id integer,
    item_quality smallint,
    item_grade smallint,
    item_exp integer,
    old_item jsonb
);

CREATE INDEX IF NOT EXISTS ix_character_item_audit_user_time
    ON character_item_audit (user_id, changed_at DESC);
