sealed partial class PacketTransactionLog
{
    private const string SchemaSql = """
        CREATE TABLE IF NOT EXISTS packet_capture_sessions (
            id uuid PRIMARY KEY,
            started_at timestamptz NOT NULL DEFAULT now(),
            capture_name varchar(128) NOT NULL DEFAULT '',
            login_host varchar(255) NOT NULL DEFAULT '',
            login_port integer NOT NULL DEFAULT 0,
            local_login_port integer NOT NULL DEFAULT 0,
            local_game_port integer NOT NULL DEFAULT 0,
            local_advertised_host varchar(255) NOT NULL DEFAULT '',
            default_game_host varchar(255),
            default_game_port integer NOT NULL DEFAULT 0,
            output_path text NOT NULL DEFAULT ''
        );

        CREATE TABLE IF NOT EXISTS packet_opcodes (
            opcode integer NOT NULL,
            direction varchar(4) NOT NULL DEFAULT 'ANY',
            name varchar(128) NOT NULL,
            category varchar(64) NOT NULL DEFAULT '',
            confidence varchar(16) NOT NULL DEFAULT 'known',
            description text NOT NULL DEFAULT '',
            notes text NOT NULL DEFAULT '',
            first_seen_at timestamptz,
            updated_at timestamptz NOT NULL DEFAULT now(),
            PRIMARY KEY (opcode, direction),
            CONSTRAINT packet_opcodes_direction_check CHECK (direction IN ('ANY', 'C2S', 'S2C'))
        );

        CREATE TABLE IF NOT EXISTS packet_transactions (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            capture_session_id uuid NOT NULL REFERENCES packet_capture_sessions (id) ON DELETE CASCADE,
            captured_at timestamptz NOT NULL DEFAULT now(),
            connection_id uuid NOT NULL,
            connection_name varchar(16) NOT NULL,
            direction varchar(4) NOT NULL,
            source_endpoint varchar(128) NOT NULL DEFAULT '',
            destination_endpoint varchar(128) NOT NULL DEFAULT '',
            chunk_sequence bigint NOT NULL,
            packet_sequence bigint NOT NULL,
            packet_index integer NOT NULL,
            stream_offset bigint NOT NULL,
            declared_length integer,
            actual_length integer NOT NULL,
            opcode integer,
            opcode_name varchar(128) NOT NULL DEFAULT 'Unknown',
            clear_bytes bytea NOT NULL,
            raw_bytes bytea NOT NULL,
            notes text NOT NULL DEFAULT ''
        );

        ALTER TABLE packet_transactions
            ADD COLUMN IF NOT EXISTS opcode_name varchar(128) NOT NULL DEFAULT 'Unknown';

        CREATE INDEX IF NOT EXISTS ix_packet_transactions_session_sequence
            ON packet_transactions (capture_session_id, packet_sequence);

        CREATE INDEX IF NOT EXISTS ix_packet_transactions_opcode
            ON packet_transactions (opcode);

        CREATE INDEX IF NOT EXISTS ix_packet_transactions_opcode_name
            ON packet_transactions (opcode_name);

        CREATE INDEX IF NOT EXISTS ix_packet_transactions_direction
            ON packet_transactions (connection_name, direction);

        CREATE INDEX IF NOT EXISTS ix_packet_transactions_captured_at
            ON packet_transactions (captured_at);

        CREATE TABLE IF NOT EXISTS npc_spawn_packets (
            map_id smallint NOT NULL,
            scene_key varchar(64) NOT NULL,
            npc_key varchar(96) NOT NULL,
            template_key varchar(128) NOT NULL,
            object_id bigint NOT NULL,
            pos_x real NOT NULL,
            pos_z real NOT NULL,
            clear_bytes bytea NOT NULL,
            detail_10077 bytea NOT NULL DEFAULT '\x'::bytea,
            detail_10080 bytea NOT NULL DEFAULT '\x'::bytea,
            source varchar(64) NOT NULL DEFAULT 'capture_proxy',
            first_seen_at timestamptz NOT NULL DEFAULT now(),
            last_seen_at timestamptz NOT NULL DEFAULT now(),
            capture_count integer NOT NULL DEFAULT 1,
            PRIMARY KEY (map_id, template_key)
        );

        ALTER TABLE npc_spawn_packets
            ADD COLUMN IF NOT EXISTS detail_10077 bytea NOT NULL DEFAULT '\x'::bytea;

        ALTER TABLE npc_spawn_packets
            ADD COLUMN IF NOT EXISTS detail_10080 bytea NOT NULL DEFAULT '\x'::bytea;

        CREATE INDEX IF NOT EXISTS ix_npc_spawn_packets_map
            ON npc_spawn_packets (map_id, npc_key);

        CREATE INDEX IF NOT EXISTS ix_npc_spawn_packets_object
            ON npc_spawn_packets (map_id, object_id);

        CREATE TABLE IF NOT EXISTS monster_spawn_packets (
            map_id smallint NOT NULL,
            scene_key varchar(96) NOT NULL,
            template_key varchar(128) NOT NULL,
            display_name varchar(255) NOT NULL DEFAULT '',
            object_id bigint NOT NULL,
            pos_x real NOT NULL,
            pos_z real NOT NULL,
            clear_bytes bytea NOT NULL,
            source varchar(64) NOT NULL DEFAULT 'capture_proxy',
            first_seen_at timestamptz NOT NULL DEFAULT now(),
            last_seen_at timestamptz NOT NULL DEFAULT now(),
            capture_count integer NOT NULL DEFAULT 1,
            PRIMARY KEY (map_id, object_id)
        );

        CREATE INDEX IF NOT EXISTS ix_monster_spawn_packets_map
            ON monster_spawn_packets (map_id, template_key);

        CREATE OR REPLACE FUNCTION set_packet_transaction_opcode_name()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            NEW.opcode_name := COALESCE((
                SELECT packet_opcodes.name
                FROM packet_opcodes
                WHERE packet_opcodes.opcode = NEW.opcode
                  AND packet_opcodes.direction IN (NEW.direction, 'ANY')
                ORDER BY CASE WHEN packet_opcodes.direction = NEW.direction THEN 0 ELSE 1 END
                LIMIT 1
            ), 'Unknown');

            RETURN NEW;
        END;
        $$;

        DROP TRIGGER IF EXISTS trg_packet_transactions_opcode_name ON packet_transactions;

        CREATE TRIGGER trg_packet_transactions_opcode_name
        BEFORE INSERT OR UPDATE OF opcode, direction
        ON packet_transactions
        FOR EACH ROW
        EXECUTE FUNCTION set_packet_transaction_opcode_name();
        """;

    private const string InsertPacketSql = """
        INSERT INTO packet_transactions (
            capture_session_id,
            captured_at,
            connection_id,
            connection_name,
            direction,
            source_endpoint,
            destination_endpoint,
            chunk_sequence,
            packet_sequence,
            packet_index,
            stream_offset,
            declared_length,
            actual_length,
            opcode,
            clear_bytes,
            raw_bytes,
            notes
        )
        VALUES (
            @capture_session_id,
            @captured_at,
            @connection_id,
            @connection_name,
            @direction,
            @source_endpoint,
            @destination_endpoint,
            @chunk_sequence,
            @packet_sequence,
            @packet_index,
            @stream_offset,
            @declared_length,
            @actual_length,
            @opcode,
            @clear_bytes,
            @raw_bytes,
            @notes
        );
        """;

    private const string UpsertNpcSpawnSql = """
        INSERT INTO npc_spawn_packets (
            map_id,
            scene_key,
            npc_key,
            template_key,
            object_id,
            pos_x,
            pos_z,
            clear_bytes,
            source,
            first_seen_at,
            last_seen_at,
            capture_count
        )
        VALUES (
            @map_id,
            @scene_key,
            @npc_key,
            @template_key,
            @object_id,
            @pos_x,
            @pos_z,
            @clear_bytes,
            'capture_proxy',
            @captured_at,
            @captured_at,
            1
        )
        ON CONFLICT (map_id, template_key) DO UPDATE
        SET object_id = EXCLUDED.object_id,
            pos_x = EXCLUDED.pos_x,
            pos_z = EXCLUDED.pos_z,
            clear_bytes = EXCLUDED.clear_bytes,
            source = EXCLUDED.source,
            last_seen_at = EXCLUDED.last_seen_at,
            capture_count = npc_spawn_packets.capture_count + 1;
        """;

    private const string UpdateNpcDetailSql = """
        UPDATE npc_spawn_packets
        SET detail_10077 = CASE WHEN @opcode = 10077 THEN @clear_bytes ELSE detail_10077 END,
            detail_10080 = CASE WHEN @opcode = 10080 THEN @clear_bytes ELSE detail_10080 END,
            last_seen_at = @captured_at
        WHERE object_id = @object_id;
        """;

    private const string UpsertMonsterSpawnSql = """
        INSERT INTO monster_spawn_packets (
            map_id,
            scene_key,
            template_key,
            display_name,
            object_id,
            pos_x,
            pos_z,
            clear_bytes,
            source,
            first_seen_at,
            last_seen_at,
            capture_count
        )
        VALUES (
            @map_id,
            @scene_key,
            @template_key,
            @display_name,
            @object_id,
            @pos_x,
            @pos_z,
            @clear_bytes,
            'capture_proxy',
            @captured_at,
            @captured_at,
            1
        )
        ON CONFLICT (map_id, object_id) DO UPDATE
        SET template_key = EXCLUDED.template_key,
            display_name = EXCLUDED.display_name,
            pos_x = EXCLUDED.pos_x,
            pos_z = EXCLUDED.pos_z,
            clear_bytes = EXCLUDED.clear_bytes,
            source = EXCLUDED.source,
            last_seen_at = EXCLUDED.last_seen_at,
            capture_count = monster_spawn_packets.capture_count + 1;
        """;
}
