<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ClCompile Include="..\src\SecureClientRuntime.cpp" />
    <ClCompile Include="..\src\SecureClientManifestBuildContract.cpp" />
    <ClCompile Include="..\src\SecureClientRuntime.Platform.cpp" />
    <ClCompile Include="..\src\SecureClientSession.cpp" />
    <ClCompile Include="..\src\SecureClientProtocol.cpp" />
    <ClCompile Include="..\src\SecureCharacterLifecycleIdentity.cpp" />
    <ClCompile Include="..\src\SecureClassSuitCommandIdentity.cpp" />
    <ClCompile Include="..\src\SecurePetCommandIdentity.cpp" />
    <ClCompile Include="..\src\SecurePetBindCommandIdentity.cpp" />
    <ClCompile Include="..\src\SecurePetAlterCommandIdentity.cpp" />
    <ClCompile Include="..\src\SecurePetManagerUtilityIdentity.cpp" />
    <ClCompile Include="..\src\SecureGameControl.cpp" />
    <ClCompile Include="..\src\SecureGameGrantRegistry.cpp" />
    <ClCompile Include="..\src\SecureEquipmentBagTransferIdentity.cpp" />
    <ClCompile Include="..\src\SecureForgeCommandIdentity.cpp" />
    <ClCompile Include="..\src\SecureHolyStoneCommandIdentity.cpp" />
    <ClCompile Include="..\src\SecureKitBagItemDeleteIdentity.cpp" />
    <ClCompile Include="..\src\SecureKitBagItemMoveIdentity.cpp" />
    <ClCompile Include="..\src\SecureLegacyCommandOperation.cpp" />
    <ClCompile Include="..\src\SecureLegacyCommandResult.cpp" />
    <ClCompile Include="..\src\SecureLegacyCommandIdentity.cpp" />
    <ClCompile Include="..\src\SecureZodiacSkillGridUpgradeIdentity.cpp" />
    <ClCompile Include="..\src\SecureZodiacSkillGridSelectionIdentity.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.Results.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.CharacterLifecycle.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.ClassSuit.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.Pets.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.EquipmentBagTransfer.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.Forge.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.HolyEquipment.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.HolyStone.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.HolyStoneCombine.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.HolyStoneImplement.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.Inventory.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.KitBagDelete.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.KitBagItemMove.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.Snapshot.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.Storage.cpp" />
    <ClCompile Include="..\src\SecurePendingOperationRegistry.Zodiac.cpp" />
    <ClCompile Include="..\src\SecureRealtimeMovementProtocol.cpp" />
    <ClCompile Include="..\src\SecureRealtimeMovementRouter.cpp" />
    <ClCompile Include="..\src\SecureOuterStream.Control.cpp" />
    <ClCompile Include="..\src\SecureOuterStream.CommandOperation.cpp" />
    <ClCompile Include="..\src\SecureOuterStream.LegacyWrite.cpp" />
    <ClCompile Include="..\src\SecureOuterStream.Binding.cpp" />
    <ClCompile Include="..\src\SecureOuterStream.cpp" />
    <ClCompile Include="..\src\SecureOuterStream.Movement.cpp" />
    <ClCompile Include="..\src\SecureUdpBindingProtocol.cpp" />
    <ClCompile Include="..\src\SecureUdpBindingGrant.cpp" />
    <ClCompile Include="..\src\SecureUdpClientChannel.cpp" />
    <ClCompile Include="..\src\SecureUdpClientChannel.Protected.cpp" />
    <ClCompile Include="..\src\SecureUdpClientChannel.Movement.cpp" />
    <ClCompile Include="..\src\SecureUdpClientWorker.cpp" />
    <ClCompile Include="..\src\SecureUdpClientWorker.Loop.cpp" />
    <ClCompile Include="..\src\SecureUdpClientWorker.Movement.cpp" />
    <ClCompile Include="..\src\SecureUdpCrypto.cpp" />
    <ClCompile Include="..\src\SecureUdpProtectedProtocol.cpp" />
    <ClCompile Include="..\src\SecureUdpReplayWindow.cpp" />
  </ItemGroup>
</Project>
