namespace Godswar.Server.Application.Characters;

internal sealed record CharacterCalculatedStatsSnapshot(
    int CharacterId,
    int AccountId,
    string Name,
    int Level,
    int MaxHp,
    int MaxMp,
    int CurrentHp,
    int CurrentMp,
    int PhysicalAttack,
    int PhysicalDefense,
    int MagicAttack,
    int MagicDefense,
    int Hit,
    int Dodge,
    int Critical,
    int CriticalResistance,
    int DamageAbsorb,
    int PhysicalDamageBonus,
    int MagicDamageBonus,
    int CureBonus,
    int BeCureBonus,
    int HpRecovery,
    int MpRecovery,
    int IgnorePhysicalDefense,
    int IgnoreMagicDefense,
    int PhysicalAppendDamage,
    int MagicAppendDamage,
    int CriticalDamagePercent,
    int CriticalDamageFlat,
    int WeaponScore,
    short WeaponRank,
    int WeaponAuraEffect,
    int ArmorScore,
    short ArmorRank,
    int ArmorAuraEffect,
    int LearnedSkillCount,
    int PhysicalDamageReduction = 0,
    int MagicDamageReduction = 0,
    int CriticalDamageReduction = 0,
    int LifeAbsorption = 0,
    int DamageRebound = 0,
    byte Profession = 0,
    int PhysicalFlatAbsorption = 0,
    int MagicFlatAbsorption = 0,
    int CriticalDamageFlatReduction = 0,
    int DamageReboundFlat = 0,
    int BasicAttackIntervalMilliseconds = 1500,
    float BasicAttackRange = 1.7f);
