$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine("// <auto-generated />")
[void]$csharp.AppendLine("// Generated from Godswar Origin NPC.INI, NpcName.dat, NPCDescription.dat, Quest.xml, NpcFun.lua, NpcFunNewMan.lua, and LuaText.lua.")
[void]$csharp.AppendLine("namespace Godswar.Server.State;")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct NpcTextTemplateSeed(string NpcKey, string SceneKey, string DisplayName, string Description);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct NpcAppearanceTemplateSeed(string TemplateKey, string NpcKey, string SceneKey, string InternalName, short? Sex, string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct NpcSpawnReferenceSeed(int QuestId, string Role, string NpcKey, short MapId, float X, float Z, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct NpcFunctionTemplateSeed(int FunctionFlag, string FunctionKey, string DisplayName, string ScriptFile, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct NpcDialogTemplateSeed(string ScriptKey, string FunctionName, short DialogIndex, int SubId, string ElementKind, string TextKey, string Text, string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal static class NpcTemplateSeeds")
[void]$csharp.AppendLine("{")
[void]$csharp.AppendLine("    public static IReadOnlyList<NpcTextTemplateSeed> Texts { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $npcTexts) {
    [void]$csharp.AppendLine("        new($(ConvertTo-CSharpString $row.NpcKey), $(ConvertTo-CSharpString $row.SceneKey), $(ConvertTo-CSharpString $row.DisplayName), $(ConvertTo-CSharpString $row.Description)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<NpcAppearanceTemplateSeed> Appearances { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $appearances) {
    [void]$csharp.AppendLine("        new($(ConvertTo-CSharpString $row.TemplateKey), $(ConvertTo-CSharpString $row.NpcKey), $(ConvertTo-CSharpString $row.SceneKey), $(ConvertTo-CSharpString $row.InternalName), $(ConvertTo-CSharpNullableShort $row.Sex), $(ConvertTo-CSharpString $row.StatsJson)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<NpcSpawnReferenceSeed> SpawnReferences { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $spawnReferences) {
    [void]$csharp.AppendLine("        new($($row.QuestId), $(ConvertTo-CSharpString $row.Role), $(ConvertTo-CSharpString $row.NpcKey), $($row.MapId), $(ConvertTo-CSharpFloat $row.X), $(ConvertTo-CSharpFloat $row.Z), $(ConvertTo-CSharpString $row.Source)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<NpcFunctionTemplateSeed> Functions { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $npcFunctions) {
    [void]$csharp.AppendLine("        new($($row.FunctionFlag), $(ConvertTo-CSharpString $row.FunctionKey), $(ConvertTo-CSharpString $row.DisplayName), $(ConvertTo-CSharpString $row.ScriptFile), $(ConvertTo-CSharpString $row.Source)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<NpcDialogTemplateSeed> Dialogs { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $dialogs) {
    [void]$csharp.AppendLine("        new($(ConvertTo-CSharpString $row.ScriptKey), $(ConvertTo-CSharpString $row.FunctionName), $($row.DialogIndex), $($row.SubId), $(ConvertTo-CSharpString $row.ElementKind), $(ConvertTo-CSharpString $row.TextKey), $(ConvertTo-CSharpString $row.Text), $(ConvertTo-CSharpString $row.StatsJson)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine("}")
