"""Level-5 forging icon installer components."""

from .common import (
    ATLAS_RELATIVE_DIRECTORY,
    EXPECTED_EXTENSION_SIZE,
    EXPECTED_TGA_DESCRIPTOR,
    EXPECTED_TGA_HEIGHT,
    EXPECTED_TGA_WIDTH,
    InstallError,
    LOCALES,
    RlePacket,
    SOURCE_ATLAS_NAME,
    SPRITE_HEIGHT,
    SPRITE_SPECS,
    SPRITE_WIDTH,
    Sprite,
    SpriteSpec,
    TARGET_ATLAS_NAME,
    TGA_FOOTER_SIGNATURE,
    TgaAtlas,
    sha256_bytes,
)
from .png_assets import load_sprites, read_png_rgba
from .tga_atlas import (
    display_pixel_index,
    encode_pixel_sequence,
    make_desired_pixels,
    parse_tga,
    patch_atlas,
    target_differs_only_in_owned_cells,
    validate_generated_atlas,
)
from .installer import (
    create_backup_directory,
    ensure_within,
    install,
    write_prepared_file,
)
from .cli import build_parser, main

__all__ = [
    "ATLAS_RELATIVE_DIRECTORY",
    "EXPECTED_EXTENSION_SIZE",
    "EXPECTED_TGA_DESCRIPTOR",
    "EXPECTED_TGA_HEIGHT",
    "EXPECTED_TGA_WIDTH",
    "InstallError",
    "LOCALES",
    "RlePacket",
    "SOURCE_ATLAS_NAME",
    "SPRITE_HEIGHT",
    "SPRITE_SPECS",
    "SPRITE_WIDTH",
    "Sprite",
    "SpriteSpec",
    "TARGET_ATLAS_NAME",
    "TGA_FOOTER_SIGNATURE",
    "TgaAtlas",
    "build_parser",
    "create_backup_directory",
    "display_pixel_index",
    "encode_pixel_sequence",
    "ensure_within",
    "install",
    "load_sprites",
    "main",
    "make_desired_pixels",
    "parse_tga",
    "patch_atlas",
    "read_png_rgba",
    "sha256_bytes",
    "target_differs_only_in_owned_cells",
    "validate_generated_atlas",
    "write_prepared_file",
]
