param(
    [string]$ClientRoot = 'C:\Godswar Origin',
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\src\Godswar.Server\State\ClassSuitItemCatalog.Generated.cs'),
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$itemBasePath = Join-Path $ClientRoot 'Localization\en_us\Settings\Sys\ItemBaseAttribute.xml'
$descriptionPath = Join-Path $ClientRoot 'Localization\en_us\Text\EquipDescription.dat'

if (-not (Test-Path -LiteralPath $itemBasePath -PathType Leaf)) {
    throw "ItemBaseAttribute source was not found: $itemBasePath"
}
if (-not (Test-Path -LiteralPath $descriptionPath -PathType Leaf)) {
    throw "EquipDescription source was not found: $descriptionPath"
}

$equipmentTypes = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase)
@(
    'weapon',
    'shield',
    'armor',
    'cloth',
    'head',
    'cuff',
    'leggins',
    'glove',
    'shoes',
    'girdle',
    'amulet',
    'ring',
    'stylish'
) | ForEach-Object { [void]$equipmentTypes.Add($_) }

# The localized equipment descriptions are exactly a color tag followed by a
# Class Suit tier. Anchoring the expression keeps prose about Class Suits (for
# example, upgrade insignias) out of this equipment-only catalog.
$classSuitDescription = [System.Text.RegularExpressions.Regex]::new(
    '^\s*(?:\|c[0-9A-Fa-f]{8})?Class\s+Suit\s+(?:IV|III|II|I)\s*(?:\|r)?\s*$',
    [System.Text.RegularExpressions.RegexOptions]::CultureInvariant)

$classSuitNameKeys = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::Ordinal)
foreach ($line in [System.IO.File]::ReadLines($descriptionPath)) {
    $parts = $line.Split([char[]]@("`t"), 2, [System.StringSplitOptions]::None)
    if ($parts.Length -ne 2 -or -not $classSuitDescription.IsMatch($parts[1])) {
        continue
    }

    $nameKey = $parts[0].Trim()
    if ([string]::IsNullOrWhiteSpace($nameKey)) {
        throw 'EquipDescription contains a Class Suit description without a name key.'
    }
    if (-not $classSuitNameKeys.Add($nameKey)) {
        throw "EquipDescription contains duplicate Class Suit key '$nameKey'."
    }
}

[xml]$itemBase = [System.IO.File]::ReadAllText($itemBasePath)
$itemNodesByName = [System.Collections.Generic.Dictionary[string, System.Xml.XmlElement]]::new(
    [System.StringComparer]::Ordinal)
foreach ($node in $itemBase.SelectNodes('/ItemBaseAttribute//*[@ID]')) {
    if ($node -isnot [System.Xml.XmlElement]) {
        continue
    }
    if (-not $classSuitNameKeys.Contains($node.Name)) {
        continue
    }
    if ($itemNodesByName.ContainsKey($node.Name)) {
        throw "ItemBaseAttribute contains duplicate Class Suit item name '$($node.Name)'."
    }
    $itemNodesByName.Add($node.Name, $node)
}

$itemIds = [System.Collections.Generic.List[uint32]]::new()
foreach ($nameKey in $classSuitNameKeys) {
    $node = $null
    if (-not $itemNodesByName.TryGetValue($nameKey, [ref]$node)) {
        throw "Class Suit description key '$nameKey' has no ItemBaseAttribute item."
    }

    $type = $node.GetAttribute('Type')
    if (-not $equipmentTypes.Contains($type) -or $node.GetAttribute('Equip') -ne '1') {
        throw "Class Suit description key '$nameKey' maps to non-equipment item type '$type'."
    }

    $itemId = [uint32]0
    if (-not [uint32]::TryParse(
            $node.GetAttribute('ID'),
            [System.Globalization.NumberStyles]::None,
            [System.Globalization.CultureInfo]::InvariantCulture,
            [ref]$itemId)) {
        throw "Class Suit item '$nameKey' has invalid ID '$($node.GetAttribute('ID'))'."
    }

    $itemIds.Add($itemId)
}

$sortedItemIds = @($itemIds | Sort-Object -Unique)
if ($sortedItemIds.Count -ne $itemIds.Count) {
    throw 'Multiple Class Suit descriptions resolve to the same item ID.'
}

$expectedItemCount = 248
if ($sortedItemIds.Count -ne $expectedItemCount) {
    throw "Expected $expectedItemCount shipped Class Suit equipment items, found $($sortedItemIds.Count)."
}

$invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture
$canonicalIds = [string]::Join(',', @(
        $sortedItemIds | ForEach-Object { $_.ToString($invariantCulture) }
    ))
$sha256 = [System.Security.Cryptography.SHA256]::Create()
try {
    $canonicalIdHashBytes = $sha256.ComputeHash(
        [System.Text.Encoding]::ASCII.GetBytes($canonicalIds))
}
finally {
    $sha256.Dispose()
}
$canonicalIdHash = [System.BitConverter]::ToString($canonicalIdHashBytes).Replace('-', '')
$itemBaseHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $itemBasePath).Hash
$descriptionHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $descriptionPath).Hash

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('// <auto-generated />')
[void]$builder.AppendLine('// Generated by tools/GenerateClassSuitItemCatalog.ps1.')
[void]$builder.AppendLine("// ItemBaseAttribute.xml SHA256: $itemBaseHash")
[void]$builder.AppendLine("// EquipDescription.dat SHA256: $descriptionHash")
[void]$builder.AppendLine("// Canonical ascending item IDs SHA256: $canonicalIdHash")
[void]$builder.AppendLine()
[void]$builder.AppendLine('namespace Godswar.Server.State;')
[void]$builder.AppendLine()
[void]$builder.AppendLine('internal static class ClassSuitItemCatalog')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine("    public const int ShippedItemCount = $expectedItemCount;")
[void]$builder.AppendLine("    public const string CanonicalItemIdSha256 = `"$canonicalIdHash`";")
[void]$builder.AppendLine()
[void]$builder.AppendLine('    private static readonly uint[] ItemIds =')
[void]$builder.AppendLine('    [')
for ($offset = 0; $offset -lt $sortedItemIds.Count; $offset += 8) {
    $last = [Math]::Min($offset + 7, $sortedItemIds.Count - 1)
    $literals = @($sortedItemIds[$offset..$last] | ForEach-Object { "$($_)u" })
    [void]$builder.AppendLine("        $([string]::Join(', ', $literals)),")
}
[void]$builder.AppendLine('    ];')
[void]$builder.AppendLine()
[void]$builder.AppendLine('    public static IReadOnlyList<uint> AllItemIds { get; } = Array.AsReadOnly(ItemIds);')
[void]$builder.AppendLine()
[void]$builder.AppendLine('    public static bool IsClassSuit(uint itemId)')
[void]$builder.AppendLine('    {')
[void]$builder.AppendLine('        return Array.BinarySearch(ItemIds, itemId) >= 0;')
[void]$builder.AppendLine('    }')
[void]$builder.AppendLine('}')

$generated = $builder.ToString()
$resolvedOutputPath = [System.IO.Path]::GetFullPath($OutputPath)
if ($Check) {
    if (-not (Test-Path -LiteralPath $resolvedOutputPath -PathType Leaf)) {
        throw "Generated catalog does not exist: $resolvedOutputPath"
    }

    $existing = [System.IO.File]::ReadAllText($resolvedOutputPath)
    if (-not [string]::Equals($existing, $generated, [System.StringComparison]::Ordinal)) {
        throw "Generated Class Suit catalog is stale: $resolvedOutputPath"
    }

    Write-Output "Class Suit catalog is up to date ($expectedItemCount items, SHA256 $canonicalIdHash)."
    return
}

$outputDirectory = [System.IO.Path]::GetDirectoryName($resolvedOutputPath)
[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[System.IO.File]::WriteAllText(
    $resolvedOutputPath,
    $generated,
    [System.Text.UTF8Encoding]::new($false))
Write-Output "Generated $expectedItemCount Class Suit item IDs at $resolvedOutputPath (SHA256 $canonicalIdHash)."
