param(
    [string]$ClientRoot = "C:\Godswar Origin",
    [string]$CSharpOutputPath = "C:\Reborn\src\Godswar.Server\State\ItemAttributeTemplateSeed.Generated.cs",
    [string]$SqlOutputPath = "C:\Reborn\database\postgres\005_item_attributes.sql"
)

$ErrorActionPreference = "Stop"

$attributePath = Join-Path $ClientRoot "Localization\en_us\Settings\Sys\ItemAppendAttribute.xml"

if (-not (Test-Path $attributePath)) {
    throw "ItemAppendAttribute.xml not found: $attributePath"
}

$invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture

function ConvertTo-CSharpString([string]$value) {
    if ($null -eq $value) {
        return 'string.Empty'
    }

    return '"' + $value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function ConvertTo-SqlString([string]$value) {
    if ($null -eq $value) {
        return 'NULL'
    }

    return "'" + $value.Replace("'", "''") + "'"
}

function ConvertTo-CSharpDecimalLiteral([decimal]$value) {
    return $value.ToString($invariantCulture) + 'm'
}

function ConvertTo-SqlNumericLiteral([decimal]$value) {
    return $value.ToString($invariantCulture)
}

function ConvertTo-SqlSmallintArray([Int16[]]$values) {
    if ($values.Count -eq 0) {
        return "ARRAY[]::smallint[]"
    }

    return "ARRAY[" + (($values | ForEach-Object { $_.ToString($invariantCulture) }) -join ",") + "]::smallint[]"
}

function ConvertTo-SqlNumericArray([decimal[]]$values) {
    if ($values.Count -eq 0) {
        return "ARRAY[]::numeric[]"
    }

    return "ARRAY[" + (($values | ForEach-Object { ConvertTo-SqlNumericLiteral $_ }) -join ",") + "]::numeric[]"
}

function ConvertTo-CSharpSmallintArray([Int16[]]$values) {
    if ($values.Count -eq 0) {
        return "[]"
    }

    return "new short[] { " + (($values | ForEach-Object { $_.ToString($invariantCulture) }) -join ", ") + " }"
}

function ConvertTo-CSharpDecimalArray([decimal[]]$values) {
    if ($values.Count -eq 0) {
        return "[]"
    }

    return "new decimal[] { " + (($values | ForEach-Object { ConvertTo-CSharpDecimalLiteral $_ }) -join ", ") + " }"
}

function Get-AttributeValue($attributes, [string]$name) {
    if ($attributes.Contains($name)) {
        return $attributes[$name]
    }

    return $null
}

[xml]$attributeXml = Get-Content $attributePath -Raw
$attributes = @(foreach ($node in $attributeXml.SelectNodes('/ItemAppendAttribute/*[@ID]')) {
    $rawAttributes = [ordered]@{}
    foreach ($attribute in $node.Attributes) {
        $rawAttributes[$attribute.Name] = $attribute.Value
    }

    $levels = @()
    foreach ($attribute in $node.Attributes) {
        if ($attribute.Name -match '^L(\d+)$') {
            $levels += [pscustomobject]@{
                Level = [int]$Matches[1]
                Value = [decimal]::Parse($attribute.Value, $invariantCulture)
            }
        }
    }

    $levelValues = [decimal[]]@(
        $levels |
            Sort-Object Level |
            ForEach-Object { $_.Value }
    )

    $distribution = [Int16[]]@()
    $distributionText = Get-AttributeValue $rawAttributes 'Distribution'
    if (-not [string]::IsNullOrWhiteSpace($distributionText)) {
        $distribution = [Int16[]]@(
            $distributionText.Split(',', [StringSplitOptions]::RemoveEmptyEntries) |
                ForEach-Object { [Int16]$_.Trim() }
        )
    }

    [pscustomobject]@{
        Id = [int](Get-AttributeValue $rawAttributes 'ID')
        NameKey = $node.Name
        StatType = [Int16](Get-AttributeValue $rawAttributes 'Type')
        Distribution = $distribution
        Percent = (Get-AttributeValue $rawAttributes 'Flag') -eq '1'
        MaxLevel = [Int16]($levelValues.Count)
        LevelValues = $levelValues
        StatsJson = ($rawAttributes | ConvertTo-Json -Compress)
    }
}) | Sort-Object Id

$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine("// <auto-generated />")
[void]$csharp.AppendLine("// Generated from Godswar Origin Localization/en_us/Settings/Sys/ItemAppendAttribute.xml.")
[void]$csharp.AppendLine("namespace Godswar.Server.State;")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct ItemAttributeTemplateSeed(")
[void]$csharp.AppendLine("    int Id,")
[void]$csharp.AppendLine("    string NameKey,")
[void]$csharp.AppendLine("    short StatType,")
[void]$csharp.AppendLine("    short[] Distribution,")
[void]$csharp.AppendLine("    bool Percent,")
[void]$csharp.AppendLine("    short MaxLevel,")
[void]$csharp.AppendLine("    decimal[] LevelValues,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal static class ItemAttributeTemplateSeeds")
[void]$csharp.AppendLine("{")
[void]$csharp.AppendLine("    public static IReadOnlyList<ItemAttributeTemplateSeed> All { get; } =")
[void]$csharp.AppendLine("    [")

foreach ($template in $attributes) {
    [void]$csharp.AppendLine(
        "        new(" +
        "$($template.Id), " +
        "$(ConvertTo-CSharpString $template.NameKey), " +
        "$($template.StatType), " +
        "$(ConvertTo-CSharpSmallintArray $template.Distribution), " +
        "$($template.Percent.ToString().ToLowerInvariant()), " +
        "$($template.MaxLevel), " +
        "$(ConvertTo-CSharpDecimalArray $template.LevelValues), " +
        "$(ConvertTo-CSharpString $template.StatsJson)),")
}

[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine("}")

$sql = [System.Text.StringBuilder]::new()
[void]$sql.AppendLine("-- <auto-generated />")
[void]$sql.AppendLine("-- Generated from Godswar Origin Localization/en_us/Settings/Sys/ItemAppendAttribute.xml.")
[void]$sql.AppendLine("CREATE TABLE IF NOT EXISTS item_attribute_templates (")
[void]$sql.AppendLine("    id integer PRIMARY KEY,")
[void]$sql.AppendLine("    name_key varchar(64) NOT NULL,")
[void]$sql.AppendLine("    stat_type smallint NOT NULL,")
[void]$sql.AppendLine("    distribution smallint[] NOT NULL DEFAULT '{}',")
[void]$sql.AppendLine("    percent boolean NOT NULL DEFAULT false,")
[void]$sql.AppendLine("    max_level smallint NOT NULL,")
[void]$sql.AppendLine("    level_values numeric[] NOT NULL DEFAULT '{}',")
[void]$sql.AppendLine("    stats jsonb NOT NULL DEFAULT '{}'::jsonb")
[void]$sql.AppendLine(");")
[void]$sql.AppendLine()
[void]$sql.AppendLine("CREATE INDEX IF NOT EXISTS ix_item_attribute_templates_stat_type ON item_attribute_templates (stat_type);")
[void]$sql.AppendLine()
[void]$sql.AppendLine("INSERT INTO item_attribute_templates (id, name_key, stat_type, distribution, percent, max_level, level_values, stats)")
[void]$sql.AppendLine("VALUES")

for ($i = 0; $i -lt $attributes.Count; $i++) {
    $template = $attributes[$i]
    $suffix = if ($i -eq $attributes.Count - 1) { "" } else { "," }
    [void]$sql.AppendLine(
        "    (" +
        "$($template.Id), " +
        "$(ConvertTo-SqlString $template.NameKey), " +
        "$($template.StatType), " +
        "$(ConvertTo-SqlSmallintArray $template.Distribution), " +
        "$($template.Percent.ToString().ToLowerInvariant()), " +
        "$($template.MaxLevel), " +
        "$(ConvertTo-SqlNumericArray $template.LevelValues), " +
        "$(ConvertTo-SqlString $template.StatsJson)::jsonb)" +
        "$suffix")
}

[void]$sql.AppendLine("ON CONFLICT (id) DO UPDATE")
[void]$sql.AppendLine("SET name_key = EXCLUDED.name_key,")
[void]$sql.AppendLine("    stat_type = EXCLUDED.stat_type,")
[void]$sql.AppendLine("    distribution = EXCLUDED.distribution,")
[void]$sql.AppendLine("    percent = EXCLUDED.percent,")
[void]$sql.AppendLine("    max_level = EXCLUDED.max_level,")
[void]$sql.AppendLine("    level_values = EXCLUDED.level_values,")
[void]$sql.AppendLine("    stats = EXCLUDED.stats;")
[void]$sql.AppendLine()

[void]$sql.AppendLine("-- character_equip is a compatibility view derived from character_items; attribute values are computed there.")
[void]$sql.AppendLine()
[void]$sql.AppendLine("CREATE OR REPLACE VIEW item_allowed_attributes AS")
[void]$sql.AppendLine("SELECT")
[void]$sql.AppendLine("    it.id AS item_id,")
[void]$sql.AppendLine("    it.kind,")
[void]$sql.AppendLine("    it.display_name AS item_name,")
[void]$sql.AppendLine("    attrs.position,")
[void]$sql.AppendLine("    attrs.attribute_id,")
[void]$sql.AppendLine("    iat.name_key,")
[void]$sql.AppendLine("    iat.stat_type,")
[void]$sql.AppendLine("    iat.percent,")
[void]$sql.AppendLine("    iat.max_level,")
[void]$sql.AppendLine("    iat.level_values")
[void]$sql.AppendLine("FROM item_templates it")
[void]$sql.AppendLine("CROSS JOIN LATERAL (")
[void]$sql.AppendLine("    SELECT")
[void]$sql.AppendLine("        attr.ordinality::smallint AS position,")
[void]$sql.AppendLine("        attr.value::integer AS attribute_id")
[void]$sql.AppendLine("    FROM regexp_split_to_table(COALESCE(it.stats->>'MainAttribute', ''), ',') WITH ORDINALITY AS attr(value, ordinality)")
[void]$sql.AppendLine("    WHERE NULLIF(attr.value, '') IS NOT NULL")
[void]$sql.AppendLine(") attrs")
[void]$sql.AppendLine("LEFT JOIN item_attribute_templates iat ON iat.id = attrs.attribute_id;")
[void]$sql.AppendLine()
[void]$sql.AppendLine("CREATE OR REPLACE VIEW character_equipment_attributes AS")
[void]$sql.AppendLine("SELECT")
[void]$sql.AppendLine("    ce.user_id,")
[void]$sql.AppendLine("    cb.name AS character_name,")
[void]$sql.AppendLine("    ce.body_part_id,")
[void]$sql.AppendLine("    ce.prop_id,")
[void]$sql.AppendLine("    it.kind,")
[void]$sql.AppendLine("    it.display_name AS item_name,")
[void]$sql.AppendLine("    attr.attribute_slot,")
[void]$sql.AppendLine("    attr.attribute_id,")
[void]$sql.AppendLine("    iat.name_key,")
[void]$sql.AppendLine("    iat.stat_type,")
[void]$sql.AppendLine("    iat.percent,")
[void]$sql.AppendLine("    COALESCE(attr.attribute_level, ce.item_grade) AS attribute_level,")
[void]$sql.AppendLine("    COALESCE(")
[void]$sql.AppendLine("        attr.attribute_value,")
[void]$sql.AppendLine("        CASE")
[void]$sql.AppendLine("            WHEN iat.level_values IS NULL THEN NULL")
[void]$sql.AppendLine("            ELSE iat.level_values[LEAST(GREATEST(COALESCE(attr.attribute_level, ce.item_grade)::integer, 1), array_length(iat.level_values, 1))]")
[void]$sql.AppendLine("        END")
[void]$sql.AppendLine("    ) AS attribute_value,")
[void]$sql.AppendLine("    EXISTS (")
[void]$sql.AppendLine("        SELECT 1")
[void]$sql.AppendLine("        FROM item_allowed_attributes iaa")
[void]$sql.AppendLine("        WHERE iaa.item_id = ce.prop_id")
[void]$sql.AppendLine("          AND iaa.attribute_id = attr.attribute_id")
[void]$sql.AppendLine("    ) AS is_allowed_for_item")
[void]$sql.AppendLine("FROM character_equip ce")
[void]$sql.AppendLine("JOIN character_base cb ON cb.id = ce.user_id")
[void]$sql.AppendLine("LEFT JOIN item_templates it ON it.id = ce.prop_id")
[void]$sql.AppendLine("CROSS JOIN LATERAL (")
[void]$sql.AppendLine("    VALUES")
[void]$sql.AppendLine("        (1::smallint, ce.type1, ce.quality1, ce.value1::numeric),")
[void]$sql.AppendLine("        (2::smallint, ce.type2, ce.quality2, ce.value2::numeric),")
[void]$sql.AppendLine("        (3::smallint, ce.type3, ce.quality3, ce.value3::numeric),")
[void]$sql.AppendLine("        (4::smallint, ce.type4, ce.quality4, ce.value4::numeric),")
[void]$sql.AppendLine("        (5::smallint, ce.type5, ce.quality5, ce.value5::numeric)")
[void]$sql.AppendLine(") attr(attribute_slot, attribute_id, attribute_level, attribute_value)")
[void]$sql.AppendLine("LEFT JOIN item_attribute_templates iat ON iat.id = attr.attribute_id")
[void]$sql.AppendLine("WHERE attr.attribute_id IS NOT NULL")
[void]$sql.AppendLine("  AND attr.attribute_id >= 0;")

New-Item -ItemType Directory -Force -Path (Split-Path $CSharpOutputPath -Parent) | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $SqlOutputPath -Parent) | Out-Null
Set-Content -Path $CSharpOutputPath -Value $csharp.ToString() -Encoding UTF8
Set-Content -Path $SqlOutputPath -Value $sql.ToString() -Encoding UTF8

Get-Item $CSharpOutputPath, $SqlOutputPath | Select-Object FullName, Length
Write-Host "Generated $($attributes.Count) item attribute templates."
