param(
    [string]$ClientRoot = "C:\Godswar Origin",
    [string]$CSharpOutputPath = "C:\Reborn\src\Godswar.Server\State\ItemTemplateSeed.Generated.cs",
    [string]$SqlOutputPath = "C:\Reborn\database\postgres\002_item_templates.sql"
)

$ErrorActionPreference = "Stop"

$itemBasePath = Join-Path $ClientRoot "Localization\en_us\Settings\Sys\ItemBaseAttribute.xml"
$equipNamePath = Join-Path $ClientRoot "Localization\en_us\Text\EquipName.dat"

if (-not (Test-Path $itemBasePath)) {
    throw "ItemBaseAttribute.xml not found: $itemBasePath"
}

if (-not (Test-Path $equipNamePath)) {
    throw "EquipName.dat not found: $equipNamePath"
}

function ConvertTo-CSharpString([string]$value) {
    if ($null -eq $value) {
        return 'string.Empty'
    }

    return '"' + $value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function ConvertTo-SqlString([string]$value) {
    if ($null -eq $value) {
        return 'NULL'
    }

    return "'" + $value.Replace("'", "''") + "'"
}

function ConvertTo-NullableIntLiteral([string]$value) {
    if ([string]::IsNullOrWhiteSpace($value)) {
        return 'null'
    }

    return [int]$value
}

function ConvertTo-SqlNullableInt([string]$value) {
    if ([string]::IsNullOrWhiteSpace($value)) {
        return 'NULL'
    }

    return [int]$value
}

function Get-AttributeValue($attributes, [string]$name) {
    if ($attributes.Contains($name)) {
        return $attributes[$name]
    }

    return $null
}

function Get-EquipmentSlot([string]$type) {
    switch ($type) {
        'head' { return 0 }
        'amulet' { return 1 }
        'glove' { return 2 }
        'armor' { return 3 }
        'cloth' { return 3 }
        'cuff' { return 4 }
        'girdle' { return 5 }
        'shoes' { return 6 }
        'leggins' { return 7 }
        'ring' { return 8 }
        'weapon' { return 10 }
        'shield' { return 11 }
        'stylish' { return 12 }
        default { return $null }
    }
}

$equipableTypes = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
@(
    'weapon',
    'shield',
    'armor',
    'cloth',
    'head',
    'cuff',
    'leggins',
    'glove',
    'shoes',
    'girdle',
    'amulet',
    'ring',
    'stylish'
) | ForEach-Object { [void]$equipableTypes.Add($_) }

$displayNames = @{}
foreach ($line in Get-Content $equipNamePath) {
    if ([string]::IsNullOrWhiteSpace($line) -or $line.StartsWith('//')) {
        continue
    }

    $parts = $line -split "`t", 2
    if ($parts.Count -eq 2 -and -not [string]::IsNullOrWhiteSpace($parts[0])) {
        $displayNames[$parts[0]] = $parts[1].Trim()
    }
}

[xml]$itemBase = Get-Content $itemBasePath -Raw
$itemNodes = $itemBase.SelectNodes('/ItemBaseAttribute//*[@ID]')
$templates = @(foreach ($node in $itemNodes) {
    $attributes = [ordered]@{}
    foreach ($attribute in $node.Attributes) {
        $attributes[$attribute.Name] = $attribute.Value
    }

    $kind = Get-AttributeValue $attributes 'Type'
    if ([string]::IsNullOrWhiteSpace($kind) -or -not $equipableTypes.Contains($kind)) {
        continue
    }

    $equipmentSlot = Get-EquipmentSlot $kind
    if ($null -eq $equipmentSlot) {
        continue
    }

    $playLevelText = Get-AttributeValue $attributes 'PlayLv'
    if ($null -eq $playLevelText) {
        $playLevelText = ''
    }

    $playLevel = $playLevelText -split ',', 2
    $minLevel = if ($playLevel.Count -ge 1) { $playLevel[0] } else { $null }
    $maxLevel = if ($playLevel.Count -ge 2) { $playLevel[1] } else { $null }
    $classIds = @()
    $classText = Get-AttributeValue $attributes 'Class'
    if (-not [string]::IsNullOrWhiteSpace($classText)) {
        $classIds = $classText.Split(',', [StringSplitOptions]::RemoveEmptyEntries) |
            ForEach-Object { [Int16]$_.Trim() }
    }

    $displayName = $displayNames[$node.Name]
    if ($null -eq $displayName) {
        $displayName = $node.Name
    }

    [pscustomobject]@{
        Id = [int]$attributes['ID']
        Kind = $kind
        NameKey = $node.Name
        DisplayName = $displayName
        EquipmentSlot = [Int16]$equipmentSlot
        ClassIds = [Int16[]]$classIds
        MinLevel = $minLevel
        MaxLevel = $maxLevel
        Hand = Get-AttributeValue $attributes 'Hand'
        SkillFlag = Get-AttributeValue $attributes 'SkillFlag'
        Texture = Get-AttributeValue $attributes 'Texture'
        Icon = Get-AttributeValue $attributes 'Icon'
        StatsJson = ($attributes | ConvertTo-Json -Compress)
    }
}) | Sort-Object Id

$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine("// <auto-generated />")
[void]$csharp.AppendLine("// Generated from Godswar Origin Localization/en_us/Settings/Sys/ItemBaseAttribute.xml.")
[void]$csharp.AppendLine("namespace Godswar.Server.State;")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct ItemTemplateSeed(")
[void]$csharp.AppendLine("    int Id,")
[void]$csharp.AppendLine("    string Kind,")
[void]$csharp.AppendLine("    string NameKey,")
[void]$csharp.AppendLine("    string DisplayName,")
[void]$csharp.AppendLine("    short EquipmentSlot,")
[void]$csharp.AppendLine("    short[] ClassIds,")
[void]$csharp.AppendLine("    int? MinLevel,")
[void]$csharp.AppendLine("    int? MaxLevel,")
[void]$csharp.AppendLine("    short? Hand,")
[void]$csharp.AppendLine("    int? SkillFlag,")
[void]$csharp.AppendLine("    string Texture,")
[void]$csharp.AppendLine("    string Icon,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal static class ItemTemplateSeeds")
[void]$csharp.AppendLine("{")
[void]$csharp.AppendLine("    public static IReadOnlyList<ItemTemplateSeed> All { get; } =")
[void]$csharp.AppendLine("    [")

foreach ($template in $templates) {
    $classIds = if ($template.ClassIds.Count -eq 0) {
        "[]"
    } else {
        "new short[] { " + (($template.ClassIds | ForEach-Object { $_.ToString() }) -join ", ") + " }"
    }

    [void]$csharp.AppendLine(
        "        new(" +
        "$($template.Id), " +
        "$(ConvertTo-CSharpString $template.Kind), " +
        "$(ConvertTo-CSharpString $template.NameKey), " +
        "$(ConvertTo-CSharpString $template.DisplayName), " +
        "$($template.EquipmentSlot), " +
        "$classIds, " +
        "$(ConvertTo-NullableIntLiteral $template.MinLevel), " +
        "$(ConvertTo-NullableIntLiteral $template.MaxLevel), " +
        "$(ConvertTo-NullableIntLiteral $template.Hand), " +
        "$(ConvertTo-NullableIntLiteral $template.SkillFlag), " +
        "$(ConvertTo-CSharpString $template.Texture), " +
        "$(ConvertTo-CSharpString $template.Icon), " +
        "$(ConvertTo-CSharpString $template.StatsJson)),")
}

[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine("}")

$sql = [System.Text.StringBuilder]::new()
[void]$sql.AppendLine("-- <auto-generated />")
[void]$sql.AppendLine("-- Generated from Godswar Origin Localization/en_us/Settings/Sys/ItemBaseAttribute.xml.")
[void]$sql.AppendLine("CREATE TABLE IF NOT EXISTS item_templates (")
[void]$sql.AppendLine("    id integer PRIMARY KEY,")
[void]$sql.AppendLine("    kind varchar(32) NOT NULL,")
[void]$sql.AppendLine("    name_key varchar(128) NOT NULL,")
[void]$sql.AppendLine("    display_name varchar(255) NOT NULL,")
[void]$sql.AppendLine("    equipment_slot smallint NOT NULL,")
[void]$sql.AppendLine("    class_ids smallint[] NOT NULL DEFAULT '{}',")
[void]$sql.AppendLine("    min_level integer,")
[void]$sql.AppendLine("    max_level integer,")
[void]$sql.AppendLine("    hand smallint,")
[void]$sql.AppendLine("    skill_flag integer,")
[void]$sql.AppendLine("    texture varchar(255) NOT NULL DEFAULT '',")
[void]$sql.AppendLine("    icon varchar(32) NOT NULL DEFAULT '',")
[void]$sql.AppendLine("    stats jsonb NOT NULL DEFAULT '{}'::jsonb")
[void]$sql.AppendLine(");")
[void]$sql.AppendLine()
[void]$sql.AppendLine("CREATE INDEX IF NOT EXISTS ix_item_templates_kind ON item_templates (kind);")
[void]$sql.AppendLine("CREATE INDEX IF NOT EXISTS ix_item_templates_equipment_slot ON item_templates (equipment_slot);")
[void]$sql.AppendLine("CREATE INDEX IF NOT EXISTS ix_item_templates_class_ids ON item_templates USING gin (class_ids);")
[void]$sql.AppendLine()
[void]$sql.AppendLine("INSERT INTO item_templates (id, kind, name_key, display_name, equipment_slot, class_ids, min_level, max_level, hand, skill_flag, texture, icon, stats)")
[void]$sql.AppendLine("VALUES")

for ($i = 0; $i -lt $templates.Count; $i++) {
    $template = $templates[$i]
    $classIds = if ($template.ClassIds.Count -eq 0) {
        "ARRAY[]::smallint[]"
    } else {
        "ARRAY[" + (($template.ClassIds | ForEach-Object { [Int16]$_ }) -join ",") + "]::smallint[]"
    }

    $suffix = if ($i -eq $templates.Count - 1) { "" } else { "," }
    [void]$sql.AppendLine(
        "    (" +
        "$($template.Id), " +
        "$(ConvertTo-SqlString $template.Kind), " +
        "$(ConvertTo-SqlString $template.NameKey), " +
        "$(ConvertTo-SqlString $template.DisplayName), " +
        "$($template.EquipmentSlot), " +
        "$classIds, " +
        "$(ConvertTo-SqlNullableInt $template.MinLevel), " +
        "$(ConvertTo-SqlNullableInt $template.MaxLevel), " +
        "$(ConvertTo-SqlNullableInt $template.Hand), " +
        "$(ConvertTo-SqlNullableInt $template.SkillFlag), " +
        "$(ConvertTo-SqlString $template.Texture), " +
        "$(ConvertTo-SqlString $template.Icon), " +
        "$(ConvertTo-SqlString $template.StatsJson)::jsonb)" +
        "$suffix")
}

[void]$sql.AppendLine("ON CONFLICT (id) DO UPDATE")
[void]$sql.AppendLine("SET kind = EXCLUDED.kind,")
[void]$sql.AppendLine("    name_key = EXCLUDED.name_key,")
[void]$sql.AppendLine("    display_name = EXCLUDED.display_name,")
[void]$sql.AppendLine("    equipment_slot = EXCLUDED.equipment_slot,")
[void]$sql.AppendLine("    class_ids = EXCLUDED.class_ids,")
[void]$sql.AppendLine("    min_level = EXCLUDED.min_level,")
[void]$sql.AppendLine("    max_level = EXCLUDED.max_level,")
[void]$sql.AppendLine("    hand = EXCLUDED.hand,")
[void]$sql.AppendLine("    skill_flag = EXCLUDED.skill_flag,")
[void]$sql.AppendLine("    texture = EXCLUDED.texture,")
[void]$sql.AppendLine("    icon = EXCLUDED.icon,")
[void]$sql.AppendLine("    stats = EXCLUDED.stats;")

New-Item -ItemType Directory -Force -Path (Split-Path $CSharpOutputPath -Parent) | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $SqlOutputPath -Parent) | Out-Null
Set-Content -Path $CSharpOutputPath -Value $csharp.ToString() -Encoding UTF8
Set-Content -Path $SqlOutputPath -Value $sql.ToString() -Encoding UTF8

Get-Item $CSharpOutputPath, $SqlOutputPath | Select-Object FullName, Length
Write-Host "Generated $($templates.Count) item templates."
