param(
    [string]$ReferenceRoot = "C:\Reborn\_reference\godswar-server",
    [string]$OutputPath = "C:\Reborn\src\Godswar.Server\Packets\ReferencePackets.Generated.cs"
)

$ErrorActionPreference = "Stop"

$items = @(
    @{Name='HashOne'; File='pkg\decode\decode.go'; Pattern='var\s+HashOne\s*=\s*\[256\]byte\s*\{(?<body>[\s\S]*?)\}'},
    @{Name='HashTwo'; File='pkg\decode\decode.go'; Pattern='var\s+HashTwo\s*=\s*\[256\]byte\s*\{(?<body>[\s\S]*?)\}'},
    @{Name='ServerList'; File='pkg\packets\server.go'; Pattern='var\s+SERVER_LIST\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='SendServer'; File='pkg\packets\server.go'; Pattern='var\s+SEND_SERVER\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='NewGameServerTemplate'; File='pkg\packets\server.go'; Pattern='var\s+NEW_GAME_SERVER_COPY\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='BlankUser'; File='pkg\packets\blank.go'; Pattern='var\s+BLANK_USER\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='AfterLogin'; File='pkg\packets\after_login_gameserver.go'; Pattern='var\s+AFTER_LOGIN\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='ServerTime'; File='pkg\experimental\athens.go'; Pattern='var\s+SERVER_TIME\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='AthensNpc'; File='pkg\experimental\athens.go'; Pattern='var\s+ATHENS_NPC\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='EnterPart1'; File='pkg\experimental\haha.go'; Pattern='var\s+ENTER_PART1\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='EnterPart2Unknown'; File='pkg\experimental\haha.go'; Pattern='var\s+ENTER_PART2_UNK\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='EnterPart2'; File='pkg\experimental\haha.go'; Pattern='var\s+ENTER_PART2\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'},
    @{Name='EnterPart4'; File='pkg\experimental\haha.go'; Pattern='var\s+ENTER_PART4\s*=\s*\[\]byte\s*\{(?<body>[\s\S]*?)\n\}'}
)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// <auto-generated />")
[void]$sb.AppendLine("// Packet constants mechanically ported from https://github.com/sush1lemon/godswar-server (GPLv3).")
[void]$sb.AppendLine("namespace Godswar.Server.Packets;")
[void]$sb.AppendLine()
[void]$sb.AppendLine("internal static class ReferencePackets")
[void]$sb.AppendLine("{")

foreach ($item in $items) {
    $sourcePath = Join-Path $ReferenceRoot $item.File
    $text = Get-Content $sourcePath -Raw
    $match = [regex]::Match($text, $item.Pattern)
    if (-not $match.Success) {
        throw "Failed to extract $($item.Name) from $($item.File)"
    }

    $body = $match.Groups['body'].Value
    $body = [regex]::Replace($body, '/\*[\s\S]*?\*/', '')
    $body = [regex]::Replace($body, '//.*', '')

    $tokens = [regex]::Matches($body, '0x[0-9A-Fa-f]{1,2}|\b\d+\b') | ForEach-Object { $_.Value }
    if ($tokens.Count -eq 0) {
        throw "No byte tokens for $($item.Name)"
    }

    [void]$sb.AppendLine("    public static ReadOnlySpan<byte> $($item.Name) => new byte[]")
    [void]$sb.AppendLine("    {")
    for ($i = 0; $i -lt $tokens.Count; $i += 16) {
        $last = [Math]::Min($i + 15, $tokens.Count - 1)
        $lineTokens = $tokens[$i..$last] | ForEach-Object {
            if ($_ -match '^0x') {
                $value = [Convert]::ToInt32($_.Substring(2), 16)
            } else {
                $value = [int]$_
            }

            if ($value -lt 0 -or $value -gt 255) {
                throw "Token '$($_)' in $($item.Name) is outside byte range"
            }

            '0x{0:X2}' -f $value
        }
        [void]$sb.AppendLine("        " + ($lineTokens -join ", ") + ",")
    }
    [void]$sb.AppendLine("    };")
    [void]$sb.AppendLine()
}

[void]$sb.AppendLine("}")

$outputDirectory = Split-Path $OutputPath -Parent
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
Set-Content -Path $OutputPath -Value $sb.ToString() -Encoding UTF8
Get-Item $OutputPath
