$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine("// <auto-generated />")
[void]$csharp.AppendLine("// Generated from Godswar Origin AddressConfig.ini, MapIdToNameConfig.ini, Scenes.dat, MapSoundConfig.xml, SpanMapConfig.xml, and map Address.ini files.")
[void]$csharp.AppendLine("namespace Godswar.Server.State;")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct MapTemplateSeed(short MapId, string SceneKey, string DisplayName, int? ClientSceneId, short? MapMode, string AddressFile, string MusicName, string EventSceneKey, string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct MapSafeAreaSeed(short MapId, short AreaIndex, float X1, float Z1, float X2, float Z2, short? Attribute);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct MapAddressPointSeed(short MapId, short GroupIndex, short PointIndex, string GroupName, string Name, float X, float Z, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct MapLinkSeed(short MapId, short LinkIndex, short TargetMapId, float X, float Z, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct MapRouteSeed(short Camp, short RouteIndex, short[] MapIds, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal static class MapTemplateSeeds")
[void]$csharp.AppendLine("{")
[void]$csharp.AppendLine("    public static IReadOnlyList<MapTemplateSeed> Maps { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $maps) {
    [void]$csharp.AppendLine("        new($($row.MapId), $(ConvertTo-CSharpString $row.SceneKey), $(ConvertTo-CSharpString $row.DisplayName), $(ConvertTo-CSharpNullableInt $row.ClientSceneId), $(ConvertTo-CSharpNullableShort $row.MapMode), $(ConvertTo-CSharpString $row.AddressFile), $(ConvertTo-CSharpString $row.MusicName), $(ConvertTo-CSharpString $row.EventSceneKey), $(ConvertTo-CSharpString $row.StatsJson)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<MapSafeAreaSeed> SafeAreas { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $safeAreas) {
    [void]$csharp.AppendLine("        new($($row.MapId), $($row.AreaIndex), $(ConvertTo-CSharpFloat $row.X1), $(ConvertTo-CSharpFloat $row.Z1), $(ConvertTo-CSharpFloat $row.X2), $(ConvertTo-CSharpFloat $row.Z2), $(ConvertTo-CSharpNullableShort $row.Attribute)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<MapAddressPointSeed> AddressPoints { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $addressPoints) {
    [void]$csharp.AppendLine("        new($($row.MapId), $($row.GroupIndex), $($row.PointIndex), $(ConvertTo-CSharpString $row.GroupName), $(ConvertTo-CSharpString $row.Name), $(ConvertTo-CSharpFloat $row.X), $(ConvertTo-CSharpFloat $row.Z), $(ConvertTo-CSharpString $row.Source)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<MapLinkSeed> Links { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $mapLinks) {
    [void]$csharp.AppendLine("        new($($row.MapId), $($row.LinkIndex), $($row.TargetMapId), $(ConvertTo-CSharpFloat $row.X), $(ConvertTo-CSharpFloat $row.Z), $(ConvertTo-CSharpString $row.Source)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<MapRouteSeed> Routes { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($row in $mapRoutes) {
    [void]$csharp.AppendLine("        new($($row.Camp), $($row.RouteIndex), $(ConvertTo-CSharpShortArray $row.MapIds), $(ConvertTo-CSharpString $row.Source)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine("}")
