-- Packet-capture metadata is part of the immutable legacy schema baseline.
-- Mutable opcode definitions remain owned by forward migrations.
CREATE TABLE IF NOT EXISTS public.packet_capture_sessions (
    id uuid PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    capture_name varchar(128) NOT NULL DEFAULT '',
    login_host varchar(255) NOT NULL DEFAULT '',
    login_port integer NOT NULL DEFAULT 0,
    local_login_port integer NOT NULL DEFAULT 0,
    local_game_port integer NOT NULL DEFAULT 0,
    local_advertised_host varchar(255) NOT NULL DEFAULT '',
    default_game_host varchar(255),
    default_game_port integer NOT NULL DEFAULT 0,
    output_path text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.packet_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capture_session_id uuid NOT NULL
        REFERENCES public.packet_capture_sessions (id) ON DELETE CASCADE,
    captured_at timestamptz NOT NULL DEFAULT now(),
    connection_id uuid NOT NULL,
    connection_name varchar(16) NOT NULL,
    direction varchar(4) NOT NULL,
    source_endpoint varchar(128) NOT NULL DEFAULT '',
    destination_endpoint varchar(128) NOT NULL DEFAULT '',
    chunk_sequence bigint NOT NULL,
    packet_sequence bigint NOT NULL,
    packet_index integer NOT NULL,
    stream_offset bigint NOT NULL,
    declared_length integer,
    actual_length integer NOT NULL,
    opcode integer,
    clear_bytes bytea NOT NULL,
    raw_bytes bytea NOT NULL,
    notes text NOT NULL DEFAULT '',
    opcode_name varchar(128) NOT NULL DEFAULT 'Unknown'
);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_session_sequence
    ON public.packet_transactions (capture_session_id, packet_sequence);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_opcode
    ON public.packet_transactions (opcode);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_direction
    ON public.packet_transactions (connection_name, direction);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_captured_at
    ON public.packet_transactions (captured_at);

CREATE INDEX IF NOT EXISTS ix_packet_transactions_opcode_name
    ON public.packet_transactions (opcode_name);

CREATE TABLE IF NOT EXISTS public.packet_opcodes (
    opcode integer NOT NULL,
    direction varchar(4) NOT NULL DEFAULT 'ANY',
    name varchar(128) NOT NULL,
    category varchar(64) NOT NULL DEFAULT '',
    confidence varchar(16) NOT NULL DEFAULT 'known',
    description text NOT NULL DEFAULT '',
    notes text NOT NULL DEFAULT '',
    first_seen_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (opcode, direction),
    CONSTRAINT packet_opcodes_direction_check
        CHECK (direction IN ('ANY', 'C2S', 'S2C'))
);

CREATE OR REPLACE FUNCTION public.set_packet_transaction_opcode_name()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.opcode_name := COALESCE((
        SELECT packet_opcodes.name
        FROM public.packet_opcodes
        WHERE packet_opcodes.opcode = NEW.opcode
          AND packet_opcodes.direction IN (NEW.direction, 'ANY')
        ORDER BY CASE
            WHEN packet_opcodes.direction = NEW.direction THEN 0
            ELSE 1
        END
        LIMIT 1
    ), 'Unknown');

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_packet_transactions_opcode_name
    ON public.packet_transactions;

CREATE TRIGGER trg_packet_transactions_opcode_name
BEFORE INSERT OR UPDATE OF opcode, direction
ON public.packet_transactions
FOR EACH ROW
EXECUTE FUNCTION public.set_packet_transaction_opcode_name();
