CREATE TABLE IF NOT EXISTS equipment_rank_rules (
    rank_kind varchar(16) NOT NULL,
    rank_level smallint NOT NULL,
    required_score integer NOT NULL,
    aura_effect integer NOT NULL,
    source varchar(64) NOT NULL,
    PRIMARY KEY (rank_kind, rank_level)
);

INSERT INTO equipment_rank_rules (rank_kind, rank_level, required_score, aura_effect, source)
VALUES
    ('weapon', 1, 40, 1, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 2, 100, 2, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 3, 180, 3, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 4, 240, 4, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 5, 300, 5, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 6, 460, 5, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 7, 600, 5, 'ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 8, 1200, 6, 'extended_ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 9, 4000, 8, 'extended_ItemBaseAttribute.ArmEffFraction'),
    ('weapon', 10, 8000, 9, 'extended_ItemBaseAttribute.ArmEffFraction'),
    ('armor', 1, 330, 1, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 2, 475, 2, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 3, 750, 3, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 4, 950, 4, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 5, 1350, 5, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 6, 1720, 6, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 7, 2225, 7, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 8, 3860, 8, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 9, 5250, 9, 'ItemBaseAttribute.DefendFraction'),
    ('armor', 10, 8000, 10, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 11, 12000, 11, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 12, 17000, 12, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 13, 22000, 13, 'extended_ItemBaseAttribute.DefendFraction'),
    ('armor', 14, 25300, 14, 'extended_ItemBaseAttribute.DefendFraction')
ON CONFLICT (rank_kind, rank_level) DO UPDATE
SET required_score = EXCLUDED.required_score,
    aura_effect = EXCLUDED.aura_effect,
    source = EXCLUDED.source;

DELETE FROM equipment_rank_rules
WHERE rank_kind = 'armor'
  AND rank_level > 14;

CREATE TABLE IF NOT EXISTS character_base (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    server_id integer REFERENCES server(id),
    name varchar(32) NOT NULL,
    gender varchar(6) NOT NULL DEFAULT 'male' CHECK (gender IN ('female', 'male')),
    "GM" smallint NOT NULL DEFAULT 0,
    camp smallint NOT NULL DEFAULT 1,
    profession smallint NOT NULL DEFAULT 0,
    fighter_job_lv integer NOT NULL DEFAULT 1,
    scholar_job_lv integer NOT NULL DEFAULT 0,
    fighter_job_exp integer NOT NULL DEFAULT 0,
    scholar_job_exp integer NOT NULL DEFAULT 0,
    "curHP" integer NOT NULL DEFAULT 1500,
    "curMP" integer NOT NULL DEFAULT 177,
    vitals_revision bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0,
    belief smallint NOT NULL DEFAULT 1,
    zodiac_type smallint NOT NULL DEFAULT 0,
    zodiac_lucky_status integer NOT NULL DEFAULT 0,
    zodiac_lucky_expires_at timestamptz,
    zodiac_level smallint NOT NULL DEFAULT 1,
    zodiac_energy integer NOT NULL DEFAULT 0,
    zodiac_energy_remainder_x100 integer NOT NULL DEFAULT 0,
    zodiac_online_day date,
    zodiac_online_duration_ticks bigint NOT NULL DEFAULT 0,
    zodiac_last_online_at timestamptz,
    zodiac_last_compensation_day date,
    zodiac_accumulated_exp_x100 integer NOT NULL DEFAULT 0,
    zodiac_accumulated_talent_exp_x100 integer NOT NULL DEFAULT 0,
    prestige integer NOT NULL DEFAULT 0,
    earl_rank smallint NOT NULL DEFAULT 0,
    consortia integer NOT NULL DEFAULT 0,
    consortia_job smallint NOT NULL DEFAULT 0,
    consortia_contribute integer NOT NULL DEFAULT 0,
    store_num integer NOT NULL DEFAULT 10,
    bag_num integer NOT NULL DEFAULT 1,
    hair_style smallint NOT NULL DEFAULT 0,
    face_shap smallint DEFAULT 0,
    "Map" smallint NOT NULL DEFAULT 1,
    "Pos_X" real NOT NULL DEFAULT 165.0,
    "Pos_Z" real NOT NULL DEFAULT -97.0,
    "Money" integer NOT NULL DEFAULT 10000,
    "Stone" integer NOT NULL DEFAULT 10,
    "SkillPoint" integer NOT NULL DEFAULT 10,
    "SkillExp" integer NOT NULL DEFAULT 0,
    holy_suit_points integer NOT NULL DEFAULT 0,
    "MaxHP" integer NOT NULL DEFAULT 1500,
    "MaxMP" integer NOT NULL DEFAULT 177,
    "Register_time" timestamptz NOT NULL DEFAULT now(),
    "LastLogin_time" timestamptz NOT NULL DEFAULT now(),
    mutetime integer DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_character_base_name ON character_base (name);
CREATE INDEX IF NOT EXISTS ix_character_base_account ON character_base (account_id);
CREATE INDEX IF NOT EXISTS ix_character_base_server ON character_base (server_id);
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS holy_suit_points integer NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS vitals_revision bigint NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_type smallint NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_lucky_status integer NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_lucky_expires_at timestamptz;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_level smallint NOT NULL DEFAULT 1;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_energy integer NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_energy_remainder_x100 integer NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_online_day date;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_online_duration_ticks bigint NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_last_online_at timestamptz;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_last_compensation_day date;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_accumulated_exp_x100 integer NOT NULL DEFAULT 0;
ALTER TABLE character_base ADD COLUMN IF NOT EXISTS zodiac_accumulated_talent_exp_x100 integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS character_experience_modifiers (
    character_id integer NOT NULL REFERENCES character_base(id) ON DELETE CASCADE,
    status_id integer NOT NULL,
    kind integer NOT NULL,
    bonus_basis_points integer NOT NULL,
    priority integer NOT NULL DEFAULT 1,
    source varchar(64) NOT NULL DEFAULT '',
    activated_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz,
    remaining_online_ticks bigint,
    PRIMARY KEY (character_id, kind)
);

ALTER TABLE character_experience_modifiers
    ADD COLUMN IF NOT EXISTS remaining_online_ticks bigint;

-- Legacy grants used wall-clock expiry. Historical online intervals
-- cannot be reconstructed, so preserve the originally granted
-- duration as the fair migration baseline instead of importing an
-- already-expired wall-clock remainder.
UPDATE character_experience_modifiers
SET remaining_online_ticks = GREATEST(
    0,
    ROUND(EXTRACT(EPOCH FROM (expires_at - activated_at)) * 10000000)::bigint)
WHERE remaining_online_ticks IS NULL
  AND expires_at IS NOT NULL;

CREATE OR REPLACE FUNCTION set_character_progression_boost_online_duration()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'UPDATE'
       AND (
           NEW.activated_at IS DISTINCT FROM OLD.activated_at
           OR NEW.expires_at IS DISTINCT FROM OLD.expires_at
       )
       AND NEW.remaining_online_ticks IS NOT DISTINCT FROM OLD.remaining_online_ticks THEN
        NEW.remaining_online_ticks := CASE
            WHEN NEW.expires_at IS NULL THEN NULL
            ELSE GREATEST(
                0,
                ROUND(EXTRACT(EPOCH FROM (
                    NEW.expires_at - NEW.activated_at
                )) * 10000000)::bigint)
        END;
    ELSIF NEW.remaining_online_ticks IS NULL AND NEW.expires_at IS NOT NULL THEN
        NEW.remaining_online_ticks := GREATEST(
            0,
            ROUND(EXTRACT(EPOCH FROM (
                NEW.expires_at - NEW.activated_at
            )) * 10000000)::bigint);
    END IF;
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_character_progression_boost_online_duration
    ON character_experience_modifiers;
CREATE TRIGGER trg_character_progression_boost_online_duration
BEFORE INSERT OR UPDATE OF activated_at, expires_at, remaining_online_ticks
    ON character_experience_modifiers
FOR EACH ROW
EXECUTE FUNCTION set_character_progression_boost_online_duration();

CREATE INDEX IF NOT EXISTS ix_character_experience_modifiers_expiry
    ON character_experience_modifiers (character_id, expires_at);

CREATE INDEX IF NOT EXISTS ix_character_experience_modifiers_online_duration
    ON character_experience_modifiers (character_id, remaining_online_ticks);

CREATE TABLE IF NOT EXISTS world_boss_areas (
    map_id smallint PRIMARY KEY REFERENCES map_templates(map_id) ON DELETE CASCADE,
    boss_template_key varchar(128) NOT NULL,
    boss_display_name varchar(255) NOT NULL DEFAULT '',
    bonus_basis_points integer NOT NULL DEFAULT 2500,
    respawn_interval_seconds integer NOT NULL DEFAULT 43200,
    enabled boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS faction_area_experience_control (
    map_id smallint PRIMARY KEY REFERENCES world_boss_areas(map_id) ON DELETE CASCADE,
    controlling_camp smallint NOT NULL CHECK (controlling_camp IN (0, 1)),
    boss_template_key varchar(128) NOT NULL,
    bonus_basis_points integer NOT NULL DEFAULT 2500,
    activated_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    death_token varchar(64) NOT NULL UNIQUE
);

CREATE INDEX IF NOT EXISTS ix_faction_area_experience_control_active
    ON faction_area_experience_control (map_id, controlling_camp, expires_at);

CREATE TABLE IF NOT EXISTS character_kitbag (
    user_id integer PRIMARY KEY REFERENCES character_base(id) ON DELETE CASCADE,
    kitbag_1 varchar(4000),
    kitbag_2 varchar(4000),
    kitbag_3 varchar(4000),
    kitbag_4 varchar(4000),
    storage varchar(4000),
    equip varchar(2000)
);

CREATE TABLE IF NOT EXISTS server_data_migrations (
    migration_key varchar(128) PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now(),
    affected_rows integer NOT NULL DEFAULT 0
);

-- Existing installations created this projection only after the legacy
-- character_kitbag data had been copied into character_items. Record
-- that completed state before recreating any inventory schema objects,
-- so deleted authoritative slots are never repopulated from stale data.
INSERT INTO server_data_migrations (migration_key, affected_rows)
SELECT '20260721_legacy_character_kitbag_import', 0
WHERE to_regclass('public.character_item_loadout') IS NOT NULL
ON CONFLICT (migration_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS character_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES character_base(id) ON DELETE CASCADE,
    item_location smallint NOT NULL,
    slot_index smallint NOT NULL,
    prop_id integer NOT NULL,
    attribute1 smallint,
    attribute2 smallint,
    attribute3 smallint,
    attribute4 smallint,
    attribute5 smallint,
    attribute_level1 smallint,
    attribute_level2 smallint,
    attribute_level3 smallint,
    attribute_level4 smallint,
    attribute_level5 smallint,
    item_quality smallint NOT NULL DEFAULT 1,
    item_grade smallint NOT NULL DEFAULT 1,
    bound smallint NOT NULL DEFAULT 1,
    stack smallint NOT NULL DEFAULT 1,
    item_exp integer NOT NULL DEFAULT 0,
    holy_suit_code integer NOT NULL DEFAULT 0,
    holy_socket_count smallint NOT NULL DEFAULT 0,
    holy_socket1_effect_id smallint,
    holy_socket1_level smallint,
    holy_socket2_effect_id smallint,
    holy_socket2_level smallint,
    holy_socket3_effect_id smallint,
    holy_socket3_level smallint,
    holy_socket4_effect_id smallint,
    holy_socket4_level smallint,
    holy_socket5_effect_id smallint,
    holy_socket5_level smallint,
    holy_socket6_effect_id smallint,
    holy_socket6_level smallint,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ux_character_items_location_slot UNIQUE (user_id, item_location, slot_index),
    CONSTRAINT ck_character_items_location CHECK (item_location IN (0, 1, 2))
);

CREATE INDEX IF NOT EXISTS ix_character_items_user_location
    ON character_items (user_id, item_location, slot_index);

CREATE TABLE IF NOT EXISTS character_item_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at timestamptz NOT NULL DEFAULT now(),
    source varchar(64) NOT NULL,
    action varchar(32) NOT NULL,
    user_id integer NOT NULL,
    item_location smallint NOT NULL,
    slot_index smallint NOT NULL,
    prop_id integer,
    item_quality smallint,
    item_grade smallint,
    item_exp integer,
    old_item jsonb
);

CREATE INDEX IF NOT EXISTS ix_character_item_audit_user_time
    ON character_item_audit (user_id, changed_at DESC);

ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket_count smallint NOT NULL DEFAULT 0;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket1_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket1_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket2_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket2_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket3_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket3_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket4_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket4_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket5_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket5_level smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket6_effect_id smallint;
ALTER TABLE character_items ADD COLUMN IF NOT EXISTS holy_socket6_level smallint;

DO $$
DECLARE
    equip_relkind "char";
BEGIN
    SELECT c.relkind
    INTO equip_relkind
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'character_equip';

    IF equip_relkind = 'r' THEN
        EXECUTE $legacy$
            INSERT INTO character_items (
                user_id, item_location, slot_index, prop_id,
                attribute1, attribute2, attribute3, attribute4, attribute5,
                attribute_level1, attribute_level2, attribute_level3, attribute_level4, attribute_level5,
                item_quality, item_grade, bound, stack, item_exp, holy_suit_code
            )
            SELECT
                ce.user_id,
                0,
                ce.body_part_id,
                ce.prop_id,
                ce.type1,
                ce.type2,
                ce.type3,
                ce.type4,
                ce.type5,
                ce.quality1,
                ce.quality2,
                ce.quality3,
                ce.quality4,
                ce.quality5,
                ce.item_quality,
                ce.item_grade,
                ce.bound,
                ce.stack,
                ce.item_exp,
                ce.holy_suit_code
            FROM character_equip ce
            ON CONFLICT (user_id, item_location, slot_index) DO NOTHING
        $legacy$;
        EXECUTE 'DROP TABLE character_equip CASCADE';
    ELSIF equip_relkind = 'v' THEN
        EXECUTE 'DROP VIEW character_equip CASCADE';
    END IF;
END $$;

