CREATE TABLE IF NOT EXISTS accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid varchar(36) NOT NULL DEFAULT '',
    email varchar(255) NOT NULL DEFAULT '',
    username varchar(32) NOT NULL,
    password varchar(255) NOT NULL DEFAULT '',
    login_status smallint NOT NULL DEFAULT 0,
    last_login_time timestamptz NOT NULL DEFAULT now(),
    last_logout_time timestamptz NOT NULL DEFAULT now(),
    last_login_ip varchar(255) NOT NULL DEFAULT '',
    last_login_mac varchar(255) NOT NULL DEFAULT '',
    total_online_time bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0,
    vip_tier smallint NOT NULL DEFAULT 0 CHECK (vip_tier BETWEEN 0 AND 4),
    vip_expires_at timestamptz
);

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS uuid varchar(36) NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS email varchar(255) NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS login_status smallint NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_login_time timestamptz NOT NULL DEFAULT now();
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_logout_time timestamptz NOT NULL DEFAULT now();
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_login_ip varchar(255) NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_login_mac varchar(255) NOT NULL DEFAULT '';
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS total_online_time bigint NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS status smallint NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS vip_tier smallint NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS vip_expires_at timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS ux_accounts_username ON accounts (username);

CREATE TABLE IF NOT EXISTS server (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    identifier varchar(25) NOT NULL,
    ip_address varchar(255) NOT NULL,
    server_limit integer NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_server_identifier ON server (identifier);

INSERT INTO server (id, name, identifier, ip_address, server_limit)
VALUES (1, 'Tempest', 'KAL3jcIzqGgKvOf1dbYZKC8cS', '127.1.1.110', 250)
ON CONFLICT (identifier) DO UPDATE
SET name = EXCLUDED.name,
    ip_address = EXCLUDED.ip_address,
    server_limit = EXCLUDED.server_limit;

CREATE TABLE IF NOT EXISTS item_templates (
    id integer PRIMARY KEY,
    kind varchar(32) NOT NULL,
    name_key varchar(128) NOT NULL,
    display_name varchar(255) NOT NULL,
    equipment_slot smallint NOT NULL,
    class_ids smallint[] NOT NULL DEFAULT '{}',
    min_level integer,
    max_level integer,
    hand smallint,
    skill_flag integer,
    texture varchar(255) NOT NULL DEFAULT '',
    icon varchar(32) NOT NULL DEFAULT '',
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_item_templates_kind ON item_templates (kind);
CREATE INDEX IF NOT EXISTS ix_item_templates_equipment_slot ON item_templates (equipment_slot);
CREATE INDEX IF NOT EXISTS ix_item_templates_class_ids ON item_templates USING gin (class_ids);

CREATE TABLE IF NOT EXISTS item_attribute_templates (
    id integer PRIMARY KEY,
    name_key varchar(64) NOT NULL,
    stat_type smallint NOT NULL,
    distribution smallint[] NOT NULL DEFAULT '{}',
    percent boolean NOT NULL DEFAULT false,
    max_level smallint NOT NULL,
    level_values numeric[] NOT NULL DEFAULT '{}',
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_item_attribute_templates_stat_type ON item_attribute_templates (stat_type);

CREATE TABLE IF NOT EXISTS class_templates (
    id smallint PRIMARY KEY,
    name varchar(32) NOT NULL UNIQUE,
    display_name varchar(64) NOT NULL,
    source varchar(128) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS talent_effect_templates (
    id smallint PRIMARY KEY,
    key varchar(32) NOT NULL UNIQUE,
    display_name varchar(128) NOT NULL,
    percent boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS talent_templates (
    id integer PRIMARY KEY,
    class_id smallint NOT NULL REFERENCES class_templates(id),
    tree_order smallint NOT NULL,
    name varchar(128) NOT NULL,
    prefix_id integer NOT NULL,
    required_prefix_rank integer NOT NULL,
    required_total_rank integer NOT NULL,
    equip_request integer NOT NULL,
    effect_type varchar(32) NOT NULL,
    effect_id smallint NOT NULL REFERENCES talent_effect_templates(id),
    effect_value numeric NOT NULL,
    is_percent boolean NOT NULL DEFAULT false,
    icon_x integer NOT NULL,
    icon_y integer NOT NULL,
    icon_width integer NOT NULL,
    icon_height integer NOT NULL,
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_talent_templates_class ON talent_templates (class_id, tree_order);

CREATE TABLE IF NOT EXISTS skill_templates (
    skill_id integer PRIMARY KEY,
    display_name varchar(128) NOT NULL,
    base_name varchar(128) NOT NULL,
    skill_level smallint,
    class_ids smallint[] NOT NULL DEFAULT '{}',
    previous_skill_id integer,
    min_level integer,
    max_level integer,
    description text NOT NULL DEFAULT '',
    target integer NOT NULL DEFAULT 0,
    affect_obj integer NOT NULL DEFAULT 0,
    distance numeric NOT NULL DEFAULT 0,
    effect_range numeric NOT NULL DEFAULT 0,
    property integer NOT NULL DEFAULT 0,
    mp integer NOT NULL DEFAULT 0,
    power1 numeric NOT NULL DEFAULT 0,
    power2 numeric NOT NULL DEFAULT 0,
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS target integer NOT NULL DEFAULT 0;
ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS affect_obj integer NOT NULL DEFAULT 0;
ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS distance numeric NOT NULL DEFAULT 0;
ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS effect_range numeric NOT NULL DEFAULT 0;
ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS property integer NOT NULL DEFAULT 0;
ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS mp integer NOT NULL DEFAULT 0;
ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS power1 numeric NOT NULL DEFAULT 0;
ALTER TABLE skill_templates ADD COLUMN IF NOT EXISTS power2 numeric NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS ix_skill_templates_class_ids ON skill_templates USING gin (class_ids);
CREATE INDEX IF NOT EXISTS ix_skill_templates_base_name ON skill_templates (base_name);

CREATE TABLE IF NOT EXISTS skill_book_templates (
    item_id integer PRIMARY KEY,
    name_key varchar(128) NOT NULL,
    display_name varchar(128) NOT NULL,
    skill_id integer NOT NULL REFERENCES skill_templates(skill_id),
    base_name varchar(128) NOT NULL,
    skill_level smallint,
    class_ids smallint[] NOT NULL DEFAULT '{}',
    min_level integer,
    max_level integer,
    previous_skill_id integer,
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_skill_book_templates_skill_id ON skill_book_templates (skill_id);
CREATE INDEX IF NOT EXISTS ix_skill_book_templates_class_ids ON skill_book_templates USING gin (class_ids);

CREATE TABLE IF NOT EXISTS npc_text_templates (
    npc_key varchar(96) PRIMARY KEY,
    scene_key varchar(64) NOT NULL DEFAULT '',
    display_name varchar(255) NOT NULL DEFAULT '',
    description text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_npc_text_templates_scene ON npc_text_templates (scene_key);

CREATE TABLE IF NOT EXISTS npc_appearance_templates (
    template_key varchar(128) PRIMARY KEY,
    npc_key varchar(96) NOT NULL,
    scene_key varchar(64) NOT NULL DEFAULT '',
    internal_name varchar(255) NOT NULL DEFAULT '',
    sex smallint,
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_npc_appearance_templates_npc_key ON npc_appearance_templates (npc_key);
CREATE INDEX IF NOT EXISTS ix_npc_appearance_templates_scene ON npc_appearance_templates (scene_key);

CREATE TABLE IF NOT EXISTS npc_spawn_references (
    quest_id integer NOT NULL,
    role varchar(16) NOT NULL,
    npc_key varchar(96) NOT NULL,
    map_id smallint NOT NULL,
    pos_x real NOT NULL,
    pos_z real NOT NULL,
    source varchar(64) NOT NULL DEFAULT '',
    PRIMARY KEY (quest_id, role, npc_key)
);

CREATE INDEX IF NOT EXISTS ix_npc_spawn_references_npc_key ON npc_spawn_references (npc_key);
CREATE INDEX IF NOT EXISTS ix_npc_spawn_references_map ON npc_spawn_references (map_id);

CREATE TABLE IF NOT EXISTS npc_spawn_packets (
    map_id smallint NOT NULL,
    scene_key varchar(64) NOT NULL,
    npc_key varchar(96) NOT NULL,
    template_key varchar(128) NOT NULL,
    object_id bigint NOT NULL,
    pos_x real NOT NULL,
    pos_z real NOT NULL,
    clear_bytes bytea NOT NULL,
    detail_10077 bytea NOT NULL DEFAULT '\x'::bytea,
    detail_10080 bytea NOT NULL DEFAULT '\x'::bytea,
    source varchar(64) NOT NULL DEFAULT 'capture_proxy',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    capture_count integer NOT NULL DEFAULT 1,
    PRIMARY KEY (map_id, template_key)
);

ALTER TABLE npc_spawn_packets
    ADD COLUMN IF NOT EXISTS detail_10077 bytea NOT NULL DEFAULT '\x'::bytea;

ALTER TABLE npc_spawn_packets
    ADD COLUMN IF NOT EXISTS detail_10080 bytea NOT NULL DEFAULT '\x'::bytea;

CREATE INDEX IF NOT EXISTS ix_npc_spawn_packets_map ON npc_spawn_packets (map_id, npc_key);
CREATE INDEX IF NOT EXISTS ix_npc_spawn_packets_object ON npc_spawn_packets (map_id, object_id);

CREATE TABLE IF NOT EXISTS monster_spawn_packets (
    map_id smallint NOT NULL,
    scene_key varchar(96) NOT NULL,
    template_key varchar(128) NOT NULL,
    display_name varchar(255) NOT NULL DEFAULT '',
    object_id bigint NOT NULL,
    pos_x real NOT NULL,
    pos_z real NOT NULL,
    clear_bytes bytea NOT NULL,
    source varchar(64) NOT NULL DEFAULT 'capture_proxy',
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    capture_count integer NOT NULL DEFAULT 1,
    PRIMARY KEY (map_id, object_id)
);

CREATE INDEX IF NOT EXISTS ix_monster_spawn_packets_map ON monster_spawn_packets (map_id, template_key);

CREATE TABLE IF NOT EXISTS server_packet_templates (
    template_key varchar(96) NOT NULL,
    sequence smallint NOT NULL,
    opcode integer NOT NULL,
    direction varchar(4) NOT NULL DEFAULT 'S2C',
    clear_bytes bytea NOT NULL,
    notes text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (template_key, sequence)
);

CREATE TABLE IF NOT EXISTS npc_function_templates (
    function_flag integer PRIMARY KEY,
    function_key varchar(64) NOT NULL UNIQUE,
    display_name varchar(255) NOT NULL DEFAULT '',
    script_file varchar(128) NOT NULL DEFAULT '',
    source varchar(64) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS npc_dialog_templates (
    script_key varchar(64) NOT NULL,
    function_name varchar(96) NOT NULL,
    dialog_index smallint NOT NULL,
    sub_id integer NOT NULL,
    element_kind varchar(32) NOT NULL,
    text_key varchar(64) NOT NULL,
    text text NOT NULL DEFAULT '',
    stats jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (script_key, function_name, dialog_index, sub_id, element_kind, text_key)
);

CREATE INDEX IF NOT EXISTS ix_npc_dialog_templates_script ON npc_dialog_templates (script_key, function_name);

CREATE TABLE IF NOT EXISTS map_templates (
    map_id smallint PRIMARY KEY,
    scene_key varchar(96) NOT NULL,
    display_name varchar(128) NOT NULL DEFAULT '',
    client_scene_id integer,
    map_mode smallint,
    address_file varchar(255) NOT NULL DEFAULT '',
    music_name varchar(128) NOT NULL DEFAULT '',
    event_scene_key varchar(128) NOT NULL DEFAULT '',
    stats jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ix_map_templates_scene_key ON map_templates (scene_key);
CREATE INDEX IF NOT EXISTS ix_map_templates_client_scene_id ON map_templates (client_scene_id);

CREATE TABLE IF NOT EXISTS map_safe_areas (
    map_id smallint NOT NULL REFERENCES map_templates(map_id) ON DELETE CASCADE,
    area_index smallint NOT NULL,
    x1 real NOT NULL,
    z1 real NOT NULL,
    x2 real NOT NULL,
    z2 real NOT NULL,
    attribute smallint,
    PRIMARY KEY (map_id, area_index)
);

CREATE TABLE IF NOT EXISTS map_address_points (
    map_id smallint NOT NULL REFERENCES map_templates(map_id) ON DELETE CASCADE,
    group_index smallint NOT NULL,
    point_index smallint NOT NULL,
    group_name varchar(128) NOT NULL DEFAULT '',
    name varchar(128) NOT NULL DEFAULT '',
    pos_x real NOT NULL,
    pos_z real NOT NULL,
    source varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (map_id, group_index, point_index)
);

CREATE INDEX IF NOT EXISTS ix_map_address_points_name ON map_address_points (name);

CREATE TABLE IF NOT EXISTS map_links (
    map_id smallint NOT NULL REFERENCES map_templates(map_id) ON DELETE CASCADE,
    link_index smallint NOT NULL,
    target_map_id smallint NOT NULL,
    pos_x real NOT NULL,
    pos_z real NOT NULL,
    source varchar(64) NOT NULL DEFAULT '',
    PRIMARY KEY (map_id, link_index, target_map_id)
);

CREATE INDEX IF NOT EXISTS ix_map_links_target ON map_links (target_map_id);

CREATE TABLE IF NOT EXISTS map_routes (
    camp smallint NOT NULL,
    route_index smallint NOT NULL,
    map_ids smallint[] NOT NULL DEFAULT '{}',
    source varchar(64) NOT NULL DEFAULT '',
    PRIMARY KEY (camp, route_index)
);

CREATE TABLE IF NOT EXISTS monster_templates (
    source_key varchar(32) NOT NULL,
    source_kind varchar(16) NOT NULL,
    source_map_id smallint,
    scene_key varchar(96) NOT NULL DEFAULT '',
    template_key varchar(128) NOT NULL,
    display_name varchar(255) NOT NULL DEFAULT '',
    rank varchar(16) NOT NULL DEFAULT 'normal',
    is_boss boolean NOT NULL DEFAULT false,
    is_elite boolean NOT NULL DEFAULT false,
    is_pet boolean NOT NULL DEFAULT false,
    attack_type smallint,
    model_file varchar(255) NOT NULL DEFAULT '',
    texture_file varchar(255) NOT NULL DEFAULT '',
    scale real,
    collision_range real,
    name_height real,
    stats jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (source_key, template_key)
);

CREATE INDEX IF NOT EXISTS ix_monster_templates_source_map ON monster_templates (source_map_id);
CREATE INDEX IF NOT EXISTS ix_monster_templates_name ON monster_templates (display_name);
CREATE INDEX IF NOT EXISTS ix_monster_templates_rank ON monster_templates (rank);

CREATE TABLE IF NOT EXISTS quest_monster_references (
    quest_id integer PRIMARY KEY,
    monster_name varchar(255) NOT NULL DEFAULT '',
    map_id smallint,
    pos_x real,
    pos_z real,
    min_level integer,
    max_level integer,
    faction smallint,
    pet_group smallint,
    source varchar(64) NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS ix_quest_monster_references_map ON quest_monster_references (map_id);
CREATE INDEX IF NOT EXISTS ix_quest_monster_references_name ON quest_monster_references (monster_name);

CREATE TABLE IF NOT EXISTS item_quality_levels (
    level smallint PRIMARY KEY,
    name varchar(32) NOT NULL,
    color varchar(64) NOT NULL
);

INSERT INTO item_quality_levels (level, name, color)
VALUES
    (1, 'Common', 'DEFAULT_TEXTCOLOR'),
    (2, 'Enhanced', 'TEAM_COLOR'),
    (3, 'Delicate', 'ItemCOLOR'),
    (4, 'Good', 'GREEN_TEXTCOLOR'),
    (5, 'Superior', 'GUILD_COLOR'),
    (6, 'Classic', 'Classical_color'),
    (7, 'Eternal', 'YELLOW_TEXTCOLOR'),
    (8, 'Epic', 'WHISPER_COLOR'),
    (9, 'Legendary', 'Legend_color'),
    (10, 'Mystic', 'Itemper_color'),
    (11, 'Divine', 'Divine_color'),
    (12, 'Celestial', 'Celestial_color'),
    (13, 'Mythical', 'Mythical_color'),
    (14, 'Astral', 'Astral_color'),
    (15, 'Arcane', 'Arcane_color'),
    (16, 'Ethereal', 'Ethereal_color'),
    (17, 'Transcendent', 'Transcendent_color'),
    (18, 'Ancient', 'Ancient_color'),
    (19, 'Primordial', 'Primordial_color'),
    (20, 'Boundless', 'Boundless_color')
ON CONFLICT (level) DO UPDATE
SET name = EXCLUDED.name,
    color = EXCLUDED.color;

CREATE TABLE IF NOT EXISTS item_grade_levels (
    level smallint PRIMARY KEY,
    stars smallint NOT NULL,
    color varchar(64) NOT NULL,
    attribute_color varchar(64) NOT NULL
);

INSERT INTO item_grade_levels (level, stars, color, attribute_color)
VALUES
    (1, 1, 'DEFAULT_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (2, 2, 'DEFAULT_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (3, 3, 'TEAM_COLOR', 'GREEN_TEXTCOLOR'),
    (4, 4, 'TEAM_COLOR', 'GREEN_TEXTCOLOR'),
    (5, 5, 'ItemCOLOR', 'GREEN_TEXTCOLOR'),
    (6, 6, 'GREEN_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (7, 7, 'GUILD_COLOR', 'GREEN_TEXTCOLOR'),
    (8, 8, 'YELLOW_TEXTCOLOR', 'GREEN_TEXTCOLOR'),
    (9, 9, 'WHISPER_COLOR', 'GREEN_TEXTCOLOR'),
    (10, 10, 'WHISPER_COLOR', 'GREEN_TEXTCOLOR'),
    (11, 11, 'Legend_color', 'GREEN_TEXTCOLOR'),
    (12, 12, 'Itemper_color', 'GREEN_TEXTCOLOR'),
    (13, 13, 'Divine_color', 'GREEN_TEXTCOLOR'),
    (14, 14, 'Divine_color', 'GREEN_TEXTCOLOR'),
    (15, 15, 'Celestial_color', 'GREEN_TEXTCOLOR'),
    (16, 16, 'Celestial_color', 'GREEN_TEXTCOLOR'),
    (17, 17, 'Mythical_color', 'GREEN_TEXTCOLOR'),
    (18, 18, 'Mythical_color', 'GREEN_TEXTCOLOR'),
    (19, 19, 'Astral_color', 'GREEN_TEXTCOLOR'),
    (20, 20, 'Arcane_color', 'GREEN_TEXTCOLOR'),
    (21, 21, 'Transcendent_color', 'GREEN_TEXTCOLOR'),
    (22, 22, 'Ancient_color', 'GREEN_TEXTCOLOR'),
    (23, 23, 'Primordial_color', 'GREEN_TEXTCOLOR'),
    (24, 24, 'Primordial_color', 'GREEN_TEXTCOLOR'),
    (25, 25, 'Boundless_color', 'GREEN_TEXTCOLOR')
ON CONFLICT (level) DO UPDATE
SET stars = EXCLUDED.stars,
    color = EXCLUDED.color,
    attribute_color = EXCLUDED.attribute_color;

