namespace Godswar.Server.State;

internal static partial class PostgresSchemaMigrationCatalog
{
    private static PostgresSchemaMigration
        CreateCommandInboxOutboxFoundation() => new(
            "20260729_025_command_inbox_outbox_foundation",
            "Create bounded command inbox, audit, and versioned outbox foundations",
            """
            ALTER TABLE public.character_talents
                ADD COLUMN outbox_revision bigint NOT NULL DEFAULT 0,
                ADD CONSTRAINT ck_character_talents_outbox_revision
                    CHECK (outbox_revision >= 0);

            CREATE TABLE public.command_audit (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                principal_type varchar(32) NOT NULL,
                principal_key varchar(128) NOT NULL,
                aggregate_type varchar(32) NOT NULL,
                aggregate_key varchar(128) NOT NULL,
                command_family varchar(64) NOT NULL,
                operation_id bytea NOT NULL,
                request_hash bytea NOT NULL,
                outcome_code varchar(32) NOT NULL,
                detail_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
                retention_policy varchar(16) NOT NULL
                    DEFAULT 'permanent',
                created_at timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT uq_command_audit_operation UNIQUE (
                    principal_type,
                    principal_key,
                    aggregate_type,
                    aggregate_key,
                    command_family,
                    operation_id
                ),
                CONSTRAINT ck_command_audit_principal_type CHECK (
                    principal_type ~ '^[a-z][a-z0-9_.-]{0,31}$'
                ),
                CONSTRAINT ck_command_audit_principal_key CHECK (
                    btrim(principal_key) <> ''
                    AND octet_length(principal_key) <= 128
                ),
                CONSTRAINT ck_command_audit_aggregate_type CHECK (
                    aggregate_type ~ '^[a-z][a-z0-9_.-]{0,31}$'
                ),
                CONSTRAINT ck_command_audit_aggregate_key CHECK (
                    btrim(aggregate_key) <> ''
                    AND octet_length(aggregate_key) <= 128
                ),
                CONSTRAINT ck_command_audit_command_family CHECK (
                    command_family ~ '^[a-z][a-z0-9_.-]{0,63}$'
                ),
                CONSTRAINT ck_command_audit_operation_id CHECK (
                    octet_length(operation_id) BETWEEN 16 AND 64
                ),
                CONSTRAINT ck_command_audit_request_hash CHECK (
                    octet_length(request_hash) = 32
                ),
                CONSTRAINT ck_command_audit_outcome CHECK (
                    outcome_code ~ '^[a-z][a-z0-9_]{0,31}$'
                ),
                CONSTRAINT ck_command_audit_detail CHECK (
                    jsonb_typeof(detail_payload) = 'object'
                    AND octet_length(detail_payload::text) <= 16384
                ),
                CONSTRAINT ck_command_audit_retention CHECK (
                    retention_policy = 'permanent'
                )
            );

            CREATE TABLE public.command_inbox (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                principal_type varchar(32) NOT NULL,
                principal_key varchar(128) NOT NULL,
                aggregate_type varchar(32) NOT NULL,
                aggregate_key varchar(128) NOT NULL,
                command_family varchar(64) NOT NULL,
                operation_id bytea NOT NULL,
                request_hash bytea NOT NULL,
                result_contract_version smallint NOT NULL,
                result_code varchar(32) NOT NULL,
                result_payload jsonb NOT NULL,
                result_hash bytea NOT NULL,
                audit_id bigint NOT NULL,
                retention_policy varchar(16) NOT NULL
                    DEFAULT 'permanent',
                duplicate_count integer NOT NULL DEFAULT 0,
                request_conflict_count integer NOT NULL DEFAULT 0,
                last_duplicate_at timestamptz,
                last_request_conflict_at timestamptz,
                completed_at timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT uq_command_inbox_operation UNIQUE (
                    principal_type,
                    principal_key,
                    aggregate_type,
                    aggregate_key,
                    command_family,
                    operation_id
                ),
                CONSTRAINT uq_command_inbox_audit UNIQUE (audit_id),
                CONSTRAINT fk_command_inbox_audit FOREIGN KEY (audit_id)
                    REFERENCES public.command_audit (id)
                    ON DELETE RESTRICT,
                CONSTRAINT ck_command_inbox_principal_type CHECK (
                    principal_type ~ '^[a-z][a-z0-9_.-]{0,31}$'
                ),
                CONSTRAINT ck_command_inbox_principal_key CHECK (
                    btrim(principal_key) <> ''
                    AND octet_length(principal_key) <= 128
                ),
                CONSTRAINT ck_command_inbox_aggregate_type CHECK (
                    aggregate_type ~ '^[a-z][a-z0-9_.-]{0,31}$'
                ),
                CONSTRAINT ck_command_inbox_aggregate_key CHECK (
                    btrim(aggregate_key) <> ''
                    AND octet_length(aggregate_key) <= 128
                ),
                CONSTRAINT ck_command_inbox_command_family CHECK (
                    command_family ~ '^[a-z][a-z0-9_.-]{0,63}$'
                ),
                CONSTRAINT ck_command_inbox_operation_id CHECK (
                    octet_length(operation_id) BETWEEN 16 AND 64
                ),
                CONSTRAINT ck_command_inbox_request_hash CHECK (
                    octet_length(request_hash) = 32
                ),
                CONSTRAINT ck_command_inbox_result_version CHECK (
                    result_contract_version BETWEEN 1 AND 32767
                ),
                CONSTRAINT ck_command_inbox_result_code CHECK (
                    result_code ~ '^[a-z][a-z0-9_]{0,31}$'
                ),
                CONSTRAINT ck_command_inbox_result_payload CHECK (
                    jsonb_typeof(result_payload) = 'object'
                    AND octet_length(result_payload::text) <= 16384
                ),
                CONSTRAINT ck_command_inbox_result_hash CHECK (
                    octet_length(result_hash) = 32
                ),
                CONSTRAINT ck_command_inbox_retention CHECK (
                    retention_policy = 'permanent'
                ),
                CONSTRAINT ck_command_inbox_duplicate_count CHECK (
                    duplicate_count BETWEEN 0 AND 1000000
                ),
                CONSTRAINT ck_command_inbox_conflict_count CHECK (
                    request_conflict_count BETWEEN 0 AND 1000000
                ),
                CONSTRAINT ck_command_inbox_duplicate_time CHECK (
                    (duplicate_count = 0 AND last_duplicate_at IS NULL)
                    OR (duplicate_count > 0 AND last_duplicate_at IS NOT NULL)
                ),
                CONSTRAINT ck_command_inbox_conflict_time CHECK (
                    (
                        request_conflict_count = 0
                        AND last_request_conflict_at IS NULL
                    )
                    OR (
                        request_conflict_count > 0
                        AND last_request_conflict_at IS NOT NULL
                    )
                )
            );

            CREATE INDEX ix_command_inbox_completed
                ON public.command_inbox (
                    command_family,
                    completed_at,
                    id
                );

            CREATE TABLE public.outbox_events (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_id uuid NOT NULL,
                command_inbox_id bigint NOT NULL,
                consumer_key varchar(64) NOT NULL,
                aggregate_type varchar(32) NOT NULL,
                aggregate_key varchar(128) NOT NULL,
                aggregate_version bigint NOT NULL,
                event_type varchar(64) NOT NULL,
                contract_version smallint NOT NULL,
                ordering_policy varchar(16) NOT NULL,
                payload jsonb NOT NULL,
                attempt_count smallint NOT NULL DEFAULT 0,
                max_attempts smallint NOT NULL DEFAULT 25,
                available_at timestamptz NOT NULL DEFAULT now(),
                lease_owner varchar(128),
                lease_token uuid,
                lease_expires_at timestamptz,
                delivered_at timestamptz,
                poisoned_at timestamptz,
                poison_reason varchar(64),
                created_at timestamptz NOT NULL DEFAULT now(),
                state_changed_at timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT uq_outbox_events_event_id UNIQUE (event_id),
                CONSTRAINT uq_outbox_events_version UNIQUE (
                    consumer_key,
                    aggregate_type,
                    aggregate_key,
                    aggregate_version
                ),
                CONSTRAINT uq_outbox_events_position_reference UNIQUE (
                    id,
                    consumer_key,
                    aggregate_type,
                    aggregate_key,
                    aggregate_version,
                    ordering_policy
                ),
                CONSTRAINT fk_outbox_events_inbox
                    FOREIGN KEY (command_inbox_id)
                    REFERENCES public.command_inbox (id)
                    ON DELETE RESTRICT,
                CONSTRAINT ck_outbox_events_consumer CHECK (
                    consumer_key ~ '^[a-z][a-z0-9_.-]{0,63}$'
                ),
                CONSTRAINT ck_outbox_events_aggregate_type CHECK (
                    aggregate_type ~ '^[a-z][a-z0-9_.-]{0,31}$'
                ),
                CONSTRAINT ck_outbox_events_aggregate_key CHECK (
                    btrim(aggregate_key) <> ''
                    AND octet_length(aggregate_key) <= 128
                ),
                CONSTRAINT ck_outbox_events_version CHECK (
                    aggregate_version > 0
                ),
                CONSTRAINT ck_outbox_events_event_type CHECK (
                    event_type ~ '^[a-z][a-z0-9_.-]{0,63}$'
                ),
                CONSTRAINT ck_outbox_events_contract_version CHECK (
                    contract_version BETWEEN 1 AND 32767
                ),
                CONSTRAINT ck_outbox_events_ordering CHECK (
                    ordering_policy IN ('strict', 'latest_wins')
                ),
                CONSTRAINT ck_outbox_events_payload CHECK (
                    jsonb_typeof(payload) = 'object'
                    AND octet_length(payload::text) <= 16384
                ),
                CONSTRAINT ck_outbox_events_attempts CHECK (
                    attempt_count BETWEEN 0 AND 100
                    AND max_attempts BETWEEN 1 AND 100
                    AND attempt_count <= max_attempts
                ),
                CONSTRAINT ck_outbox_events_lease CHECK (
                    (
                        lease_owner IS NULL
                        AND lease_token IS NULL
                        AND lease_expires_at IS NULL
                    )
                    OR (
                        lease_owner IS NOT NULL
                        AND btrim(lease_owner) <> ''
                        AND octet_length(lease_owner) <= 128
                        AND lease_token IS NOT NULL
                        AND lease_expires_at IS NOT NULL
                        AND delivered_at IS NULL
                        AND poisoned_at IS NULL
                    )
                ),
                CONSTRAINT ck_outbox_events_terminal_state CHECK (
                    NOT (
                        delivered_at IS NOT NULL
                        AND poisoned_at IS NOT NULL
                    )
                ),
                CONSTRAINT ck_outbox_events_poison_reason CHECK (
                    (poisoned_at IS NULL AND poison_reason IS NULL)
                    OR (
                        poisoned_at IS NOT NULL
                        AND poison_reason IS NOT NULL
                        AND btrim(poison_reason) <> ''
                    )
                ),
                CONSTRAINT ck_outbox_events_times CHECK (
                    available_at >= created_at
                    AND state_changed_at >= created_at
                    AND (
                        delivered_at IS NULL
                        OR delivered_at >= created_at
                    )
                    AND (
                        poisoned_at IS NULL
                        OR poisoned_at >= created_at
                    )
                )
            );

            CREATE INDEX ix_outbox_events_pending
                ON public.outbox_events (
                    consumer_key,
                    available_at,
                    lease_expires_at,
                    id
                )
                WHERE delivered_at IS NULL
                  AND poisoned_at IS NULL;

            CREATE INDEX ix_outbox_events_expired_lease
                ON public.outbox_events (lease_expires_at, id)
                WHERE lease_expires_at IS NOT NULL
                  AND delivered_at IS NULL
                  AND poisoned_at IS NULL;

            CREATE INDEX ix_outbox_events_poison
                ON public.outbox_events (
                    consumer_key,
                    poisoned_at,
                    id
                )
                WHERE poisoned_at IS NOT NULL;

            CREATE INDEX ix_outbox_events_inbox
                ON public.outbox_events (command_inbox_id, id);

            CREATE TABLE public.outbox_consumer_positions (
                consumer_key varchar(64) NOT NULL,
                aggregate_type varchar(32) NOT NULL,
                aggregate_key varchar(128) NOT NULL,
                ordering_policy varchar(16) NOT NULL,
                current_version bigint NOT NULL DEFAULT 0,
                inflight_event_id bigint,
                inflight_version bigint,
                lease_owner varchar(128),
                lease_token uuid,
                lease_expires_at timestamptz,
                updated_at timestamptz NOT NULL DEFAULT now(),
                CONSTRAINT pk_outbox_consumer_positions PRIMARY KEY (
                    consumer_key,
                    aggregate_type,
                    aggregate_key
                ),
                CONSTRAINT fk_outbox_positions_inflight
                    FOREIGN KEY (
                        inflight_event_id,
                        consumer_key,
                        aggregate_type,
                        aggregate_key,
                        inflight_version,
                        ordering_policy
                    )
                    REFERENCES public.outbox_events (
                        id,
                        consumer_key,
                        aggregate_type,
                        aggregate_key,
                        aggregate_version,
                        ordering_policy
                    )
                    ON DELETE RESTRICT,
                CONSTRAINT ck_outbox_positions_consumer CHECK (
                    consumer_key ~ '^[a-z][a-z0-9_.-]{0,63}$'
                ),
                CONSTRAINT ck_outbox_positions_aggregate_type CHECK (
                    aggregate_type ~ '^[a-z][a-z0-9_.-]{0,31}$'
                ),
                CONSTRAINT ck_outbox_positions_aggregate_key CHECK (
                    btrim(aggregate_key) <> ''
                    AND octet_length(aggregate_key) <= 128
                ),
                CONSTRAINT ck_outbox_positions_ordering CHECK (
                    ordering_policy IN ('strict', 'latest_wins')
                ),
                CONSTRAINT ck_outbox_positions_current_version CHECK (
                    current_version >= 0
                ),
                CONSTRAINT ck_outbox_positions_inflight CHECK (
                    (
                        inflight_event_id IS NULL
                        AND inflight_version IS NULL
                        AND lease_owner IS NULL
                        AND lease_token IS NULL
                        AND lease_expires_at IS NULL
                    )
                    OR (
                        inflight_event_id IS NOT NULL
                        AND inflight_version IS NOT NULL
                        AND inflight_version > current_version
                        AND (
                            ordering_policy <> 'strict'
                            OR inflight_version - current_version = 1
                        )
                        AND lease_owner IS NOT NULL
                        AND btrim(lease_owner) <> ''
                        AND octet_length(lease_owner) <= 128
                        AND lease_token IS NOT NULL
                        AND lease_expires_at IS NOT NULL
                    )
                )
            );

            CREATE INDEX ix_outbox_consumer_positions_lease
                ON public.outbox_consumer_positions (
                    lease_expires_at,
                    consumer_key,
                    aggregate_type,
                    aggregate_key
                )
                WHERE inflight_event_id IS NOT NULL;
            """ + "\n\n" + CommandInboxOutboxGuardsSql);
}
