namespace Godswar.Server.State;

internal static partial class PostgresSchemaMigrationCatalog
{
    private static PostgresSchemaMigration CreatePetManagerUtility() =>
        new(
            "20260813_089_pet_manager_utility",
            "Persist sealed-pet links and Pet Manager utility evidence",
            """
            ALTER TABLE public.pet_operation_audit
                ADD CONSTRAINT ck_pet_operation_audit_operation_v8
                CHECK (
                    operation IN (
                        'owner_merge',
                        'pet_merge',
                        'rebirth',
                        'soul_contract',
                        'take',
                        'summon',
                        'dismiss',
                        'reveal_growth',
                        'reset_basic_savvy',
                        'change_appearance',
                        'bind',
                        'seal',
                        'unseal',
                        'hatch',
                        'level_up',
                        'check_growth',
                        'claim_pet_call',
                        'claim_merge',
                        'change_gender'
                    )
                ) NOT VALID;

            ALTER TABLE public.pet_operation_audit
                VALIDATE CONSTRAINT
                    ck_pet_operation_audit_operation_v8;

            ALTER TABLE public.pet_operation_audit
                DROP CONSTRAINT pet_operation_audit_operation_check;

            ALTER TABLE public.pet_operation_audit
                RENAME CONSTRAINT
                    ck_pet_operation_audit_operation_v8
                TO pet_operation_audit_operation_check;

            CREATE TABLE public.sealed_pet_items (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                item_instance_id bigint NOT NULL UNIQUE
                    REFERENCES public.character_items(id)
                    ON DELETE RESTRICT,
                pet_id bigint NOT NULL UNIQUE
                    REFERENCES public.character_pets(id)
                    ON DELETE RESTRICT,
                owner_character_id integer NOT NULL
                    REFERENCES public.character_base(id)
                    ON DELETE RESTRICT,
                seal_request_id uuid NOT NULL UNIQUE,
                item_instance_id_snapshot bigint NOT NULL,
                pet_id_snapshot bigint NOT NULL,
                owner_character_id_snapshot integer NOT NULL,
                pet_species_id_snapshot smallint NOT NULL,
                pet_name_snapshot varchar(32) NOT NULL,
                sealed_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
                CONSTRAINT ck_sealed_pet_item_snapshot_identity CHECK (
                    item_instance_id_snapshot = item_instance_id
                    AND pet_id_snapshot = pet_id
                ),
                CONSTRAINT ck_sealed_pet_item_name CHECK (
                    btrim(pet_name_snapshot) <> ''
                )
            );

            CREATE INDEX ix_sealed_pet_items_owner
                ON public.sealed_pet_items (owner_character_id, item_instance_id);

            CREATE OR REPLACE FUNCTION
                public.sync_sealed_pet_item_owner()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $sync_owner$
            DECLARE
                linked_pet_id bigint;
            BEGIN
                IF NEW.user_id IS NOT DISTINCT FROM OLD.user_id THEN
                    RETURN NEW;
                END IF;
                SELECT link.pet_id INTO linked_pet_id
                FROM public.sealed_pet_items link
                WHERE link.item_instance_id = OLD.id
                FOR UPDATE;
                IF linked_pet_id IS NULL THEN
                    RETURN NEW;
                END IF;

                UPDATE public.character_pets
                SET user_id = NEW.user_id,
                    revision = revision + 1,
                    updated_at = transaction_timestamp()
                WHERE id = linked_pet_id
                  AND user_id = OLD.user_id
                  AND activity_state = 'sealed';
                IF NOT FOUND THEN
                    RAISE EXCEPTION
                        'Cannot transfer invalid sealed pet %',
                        linked_pet_id;
                END IF;

                UPDATE public.sealed_pet_items
                SET owner_character_id = NEW.user_id
                WHERE item_instance_id = OLD.id
                  AND owner_character_id = OLD.user_id;
                IF NOT FOUND THEN
                    RAISE EXCEPTION
                        'Cannot transfer invalid packed item %',
                        OLD.id;
                END IF;
                RETURN NEW;
            END
            $sync_owner$;

            CREATE TRIGGER trg_sealed_pet_item_owner_sync
            BEFORE UPDATE OF user_id
            ON public.character_items
            FOR EACH ROW EXECUTE FUNCTION
                public.sync_sealed_pet_item_owner();

            CREATE OR REPLACE FUNCTION
                public.validate_active_sealed_pet_link(
                    target_item_id bigint,
                    target_pet_id bigint)
            RETURNS void
            LANGUAGE plpgsql
            AS $validate$
            DECLARE
                link_row public.sealed_pet_items%ROWTYPE;
                item_owner integer;
                item_template integer;
                pet_owner integer;
                pet_state varchar(16);
                pet_carried boolean;
                pet_summoned boolean;
                pet_contributes boolean;
            BEGIN
                SELECT * INTO link_row
                FROM public.sealed_pet_items link
                WHERE (target_item_id IS NOT NULL
                       AND link.item_instance_id = target_item_id)
                   OR (target_pet_id IS NOT NULL
                       AND link.pet_id = target_pet_id);
                IF NOT FOUND THEN
                    RETURN;
                END IF;

                SELECT item.user_id, item.prop_id
                INTO item_owner, item_template
                FROM public.character_items item
                WHERE item.id = link_row.item_instance_id;

                SELECT pet.user_id, pet.activity_state,
                       pet.is_carried, pet.is_summoned,
                       pet.contributes_to_character
                INTO pet_owner, pet_state, pet_carried,
                     pet_summoned, pet_contributes
                FROM public.character_pets pet
                WHERE pet.id = link_row.pet_id;

                IF item_owner IS NULL OR pet_owner IS NULL
                   OR item_template <> 10109
                   OR item_owner <> link_row.owner_character_id
                   OR pet_owner <> link_row.owner_character_id
                   OR pet_state <> 'sealed'
                   OR pet_carried OR pet_summoned OR pet_contributes THEN
                    RAISE EXCEPTION
                        'Invalid active sealed-pet link item %, pet %',
                        link_row.item_instance_id,
                        link_row.pet_id;
                END IF;
            END
            $validate$;

            CREATE OR REPLACE FUNCTION
                public.validate_active_sealed_pet_link_trigger()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $trigger$
            BEGIN
                IF TG_TABLE_NAME = 'sealed_pet_items' THEN
                    PERFORM public.validate_active_sealed_pet_link(
                        NEW.item_instance_id,
                        NEW.pet_id);
                ELSIF TG_TABLE_NAME = 'character_items' THEN
                    PERFORM public.validate_active_sealed_pet_link(
                        COALESCE(NEW.id, OLD.id),
                        NULL);
                ELSE
                    PERFORM public.validate_active_sealed_pet_link(
                        NULL,
                        COALESCE(NEW.id, OLD.id));
                END IF;
                RETURN NULL;
            END
            $trigger$;

            CREATE CONSTRAINT TRIGGER
                trg_sealed_pet_items_validate
            AFTER INSERT OR UPDATE
            ON public.sealed_pet_items
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION
                public.validate_active_sealed_pet_link_trigger();

            CREATE CONSTRAINT TRIGGER
                trg_sealed_pet_item_authority_validate
            AFTER UPDATE OR DELETE
            ON public.character_items
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION
                public.validate_active_sealed_pet_link_trigger();

            CREATE CONSTRAINT TRIGGER
                trg_sealed_pet_authority_validate
            AFTER UPDATE OR DELETE
            ON public.character_pets
            DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION
                public.validate_active_sealed_pet_link_trigger();

            CREATE OR REPLACE VIEW public.pet_durable_command_evidence AS
            SELECT
                inbox.id AS inbox_id,
                inbox.principal_key AS account_id,
                inbox.aggregate_key,
                inbox.command_family,
                encode(inbox.operation_id, 'hex') AS operation_id,
                inbox.result_code,
                inbox.duplicate_count,
                inbox.request_conflict_count,
                inbox.completed_at,
                audit.id AS audit_id,
                event.event_id,
                event.aggregate_version,
                event.delivered_at,
                event.poisoned_at
            FROM public.command_inbox inbox
            INNER JOIN public.command_audit audit
                ON audit.id = inbox.audit_id
            LEFT JOIN public.outbox_events event
                ON event.command_inbox_id = inbox.id
               AND event.consumer_key = 'pet_durable_v1'
            WHERE inbox.aggregate_type = 'character_pet_value'
              AND inbox.command_family IN (
                  'bag_item_activation',
                  'pet_level_upgrade',
                  'pet_presence_transition',
                  'pet_skill_unlearn',
                  'pet_growth_reset',
                  'pet_basic_savvy_reset',
                  'pet_owner_merge_toggle',
                  'pet_to_pet_merge',
                  'pet_rebirth',
                  'pet_appearance_change',
                  'pet_bind',
                  'pet_soul_contract',
                  'pet_manager_utility'
              );

            INSERT INTO packet_opcodes (
                opcode, direction, name, category,
                confidence, description, notes
            )
            VALUES
                (
                    10283, 'C2S', 'PackedPetDetailRequest', 'pets',
                    'known',
                    'Requests the pet linked to an owned packed Seal Jade.',
                    'Eight-byte frame: header plus uint32 pet ID; server authorizes the active item link.'
                ),
                (
                    10284, 'S2C', 'PackedPetDetailResponse', 'pets',
                    'known',
                    'Returns one authorized packed-pet detail record.',
                    '172-byte frame: four-byte header plus the native 168-byte pet record.'
                )
            ON CONFLICT (opcode, direction) DO UPDATE
            SET name = EXCLUDED.name,
                category = EXCLUDED.category,
                confidence = EXCLUDED.confidence,
                description = EXCLUDED.description,
                notes = EXCLUDED.notes,
                updated_at = transaction_timestamp();
            """);
}
