namespace Godswar.Server.State;

internal static partial class PostgresSchemaMigrationCatalog
{
    private static PostgresSchemaMigration
        ReconcileStockHolyStoneMaterialTemplates() => new(
        "20260804_058_stock_holy_stone_material_templates",
        "Reconcile all stock Holy Stone materials for immutable publication",
        """
        WITH materials(
            id, name_key, display_name, texture, icon, overlap, special_flag
        ) AS (
            VALUES
                (9030, 'Stone9030', 'Heated Holy Stone',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '252,0', '1', 'PreStone'),
                (9031, 'Stone9031', 'Cooled Holy Stone',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '288,0', '1', 'PreStone'),
                (9040, 'Stone9040', 'Level 1 Eclipse Stone',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '828,900', '99', NULL),
                (9041, 'Stone9041', 'Level 2 Eclipse Stone',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '864,900', '99', NULL),
                (9042, 'Stone9042', 'Level 3 Eclipse Stone',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '900,900', '99', NULL),
                (9050, 'Stone9050', 'Goddess'' Stone',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '324,0', '99', NULL),
                (9051, 'Stone9051', 'Copper Evasion Signet',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '540,936', '99', NULL),
                (9052, 'Stone9052', 'Silver Evasion Signet',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '576,936', '99', NULL),
                (9053, 'Stone9053', 'Gold Evasion Signet',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '612,936', '99', NULL),
                (9054, 'Stone9054', 'Gold Evasion Signet',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '612,936', '99', NULL),
                (9055, 'Stone9055', 'Gold Evasion Signet',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '612,936', '99', NULL),
                (9056, 'Stone9056', 'Gold Evasion Signet',
                    './Localization/en_us/UI/Texture/Icon.gwo',
                    '612,936', '99', NULL),
                (9060, 'Firegholiness1', 'Fire Spirit of Destruction',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '360,0', '99', NULL),
                (9061, 'Firegholiness2', 'Fire Spirit of Penetration',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '396,0', '99', NULL),
                (9062, 'Firegholiness3', 'Fire Spirit of Fist',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '432,0', '99', NULL),
                (9063, 'Firegholiness4', 'Fire Spirit of Fiery',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '468,0', '99', NULL),
                (9064, 'Firegholiness5', 'Fire Spirit of Blood',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '504,0', '99', NULL),
                (9065, 'Firegholiness6', 'Fire Spirit of Pressure',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '540,0', '99', NULL),
                (9066, 'Firegholiness7', 'Fire Spirit of Assail',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '864,0', '99', NULL),
                (9067, 'Firegholiness8', 'Fire Spirit of Lightning',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '900,0', '99', NULL),
                (9068, 'Waterholiness9', 'Water Spirit of Renewal',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '756,36', '99', NULL),
                (9069, 'Waterholiness10', 'Water Spirit of Vitality',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '792,36', '99', NULL),
                (9080, 'Waterholiness1', 'Water Spirit of Darkness',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '576,0', '99', NULL),
                (9081, 'Waterholiness2', 'Water Spirit of Mist',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '612,0', '99', NULL),
                (9082, 'Waterholiness3', 'Water Spirit of Silence',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '648,0', '99', NULL),
                (9083, 'Waterholiness4', 'Water Spirit of Chillness',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '684,0', '99', NULL),
                (9084, 'Waterholiness5', 'Water Spirit of Ice',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '720,0', '99', NULL),
                (9085, 'Waterholiness6', 'Water Spirit of Frost',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '756,0', '99', NULL),
                (9086, 'Waterholiness7', 'Water Spirit of Intent',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '792,0', '99', NULL),
                (9087, 'Waterholiness8', 'Water Spirit of Resilience',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '828,0', '99', NULL),
                (9088, 'Firegholiness9', 'Fire Spirit of Flow',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '828,36', '99', NULL),
                (9089, 'Firegholiness10', 'Fire Spirit of Tranquility',
                    './Localization/en_us/UI/Texture/Icon2.gwo',
                    '864,36', '99', NULL)
        )
        INSERT INTO public.item_templates (
            id, kind, name_key, display_name, equipment_slot, class_ids,
            min_level, max_level, hand, skill_flag, texture, icon, stats
        )
        SELECT
            material.id,
            'consume item',
            material.name_key,
            material.display_name,
            0,
            '{}'::smallint[],
            NULL,
            NULL,
            NULL,
            NULL,
            material.texture,
            material.icon,
            jsonb_strip_nulls(jsonb_build_object(
                'ID', material.id::text,
                'Type', 'consume item',
                'Texture', material.texture,
                'Icon', material.icon,
                'Random', '0',
                'Distribution', '0,0',
                'Money', '0',
                'Overlap', material.overlap,
                'SpecialFlag', material.special_flag
            ))
        FROM materials AS material
        ON CONFLICT (id) DO UPDATE
        SET kind = EXCLUDED.kind,
            name_key = EXCLUDED.name_key,
            display_name = EXCLUDED.display_name,
            equipment_slot = EXCLUDED.equipment_slot,
            class_ids = EXCLUDED.class_ids,
            min_level = EXCLUDED.min_level,
            max_level = EXCLUDED.max_level,
            hand = EXCLUDED.hand,
            skill_flag = EXCLUDED.skill_flag,
            texture = EXCLUDED.texture,
            icon = EXCLUDED.icon,
            stats = EXCLUDED.stats;
        """);
}
