$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine("// <auto-generated />")
[void]$csharp.AppendLine("// Generated from Godswar Origin Skill.ini, Magic.ini, ItemBaseAttribute.xml, EquipName.dat, and SkillInfo.dat.")
[void]$csharp.AppendLine("namespace Godswar.Server.State;")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct ClassTemplateSeed(short Id, string Name, string DisplayName, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct TalentEffectTemplateSeed(short Id, string Key, string DisplayName, bool Percent);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct TalentTemplateSeed(")
[void]$csharp.AppendLine("    int Id,")
[void]$csharp.AppendLine("    short ClassId,")
[void]$csharp.AppendLine("    short TreeOrder,")
[void]$csharp.AppendLine("    string Name,")
[void]$csharp.AppendLine("    int PrefixId,")
[void]$csharp.AppendLine("    int RequiredPrefixRank,")
[void]$csharp.AppendLine("    int RequiredTotalRank,")
[void]$csharp.AppendLine("    int EquipRequest,")
[void]$csharp.AppendLine("    string EffectType,")
[void]$csharp.AppendLine("    short EffectId,")
[void]$csharp.AppendLine("    decimal EffectValue,")
[void]$csharp.AppendLine("    bool IsPercent,")
[void]$csharp.AppendLine("    int IconX,")
[void]$csharp.AppendLine("    int IconY,")
[void]$csharp.AppendLine("    int IconWidth,")
[void]$csharp.AppendLine("    int IconHeight,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct SkillTemplateSeed(")
[void]$csharp.AppendLine("    int SkillId,")
[void]$csharp.AppendLine("    string DisplayName,")
[void]$csharp.AppendLine("    string BaseName,")
[void]$csharp.AppendLine("    short? SkillLevel,")
[void]$csharp.AppendLine("    short[] ClassIds,")
[void]$csharp.AppendLine("    int? PreviousSkillId,")
[void]$csharp.AppendLine("    int? MinLevel,")
[void]$csharp.AppendLine("    int? MaxLevel,")
[void]$csharp.AppendLine("    string Description,")
[void]$csharp.AppendLine("    int Target,")
[void]$csharp.AppendLine("    int AffectObj,")
[void]$csharp.AppendLine("    decimal Distance,")
[void]$csharp.AppendLine("    decimal Range,")
[void]$csharp.AppendLine("    int Property,")
[void]$csharp.AppendLine("    int Mp,")
[void]$csharp.AppendLine("    decimal Power1,")
[void]$csharp.AppendLine("    decimal Power2,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct SkillBookTemplateSeed(")
[void]$csharp.AppendLine("    int ItemId,")
[void]$csharp.AppendLine("    string NameKey,")
[void]$csharp.AppendLine("    string DisplayName,")
[void]$csharp.AppendLine("    int SkillId,")
[void]$csharp.AppendLine("    string BaseName,")
[void]$csharp.AppendLine("    short? SkillLevel,")
[void]$csharp.AppendLine("    short[] ClassIds,")
[void]$csharp.AppendLine("    int? MinLevel,")
[void]$csharp.AppendLine("    int? MaxLevel,")
[void]$csharp.AppendLine("    int? PreviousSkillId,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal static class SkillTalentSeeds")
[void]$csharp.AppendLine("{")
[void]$csharp.AppendLine("    public static IReadOnlyList<ClassTemplateSeed> Classes { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($class in $classes) {
    [void]$csharp.AppendLine("        new($($class.Id), $(ConvertTo-CSharpString $class.Name), $(ConvertTo-CSharpString $class.DisplayName), $(ConvertTo-CSharpString $class.Source)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<TalentEffectTemplateSeed> TalentEffects { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($effect in $talentEffects) {
    [void]$csharp.AppendLine("        new($($effect.Id), $(ConvertTo-CSharpString $effect.Key), $(ConvertTo-CSharpString $effect.DisplayName), $($effect.Percent.ToString().ToLowerInvariant())),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<TalentTemplateSeed> Talents { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($talent in $talents) {
    [void]$csharp.AppendLine(
        "        new(" +
        "$($talent.Id), $($talent.ClassId), $($talent.TreeOrder), " +
        "$(ConvertTo-CSharpString $talent.Name), $($talent.PrefixId), $($talent.RequiredPrefixRank), $($talent.RequiredTotalRank), $($talent.EquipRequest), " +
        "$(ConvertTo-CSharpString $talent.EffectType), $($talent.EffectId), $(ConvertTo-CSharpDecimal $talent.EffectValue), $($talent.IsPercent.ToString().ToLowerInvariant()), " +
        "$($talent.IconX), $($talent.IconY), $($talent.IconWidth), $($talent.IconHeight), $(ConvertTo-CSharpString $talent.StatsJson)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<SkillTemplateSeed> Skills { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($skill in $skills) {
    [void]$csharp.AppendLine(
        "        new(" +
        "$($skill.SkillId), $(ConvertTo-CSharpString $skill.DisplayName), $(ConvertTo-CSharpString $skill.BaseName), $(ConvertTo-CSharpNullableShort $skill.SkillLevel), " +
        "$(ConvertTo-CSharpShortArray $skill.ClassIds), $(ConvertTo-CSharpNullableInt $skill.PreviousSkillId), $(ConvertTo-CSharpNullableInt $skill.MinLevel), $(ConvertTo-CSharpNullableInt $skill.MaxLevel), " +
        "$(ConvertTo-CSharpString $skill.Description), $($skill.Target), $($skill.AffectObj), $(ConvertTo-CSharpDecimal $skill.Distance), $(ConvertTo-CSharpDecimal $skill.Range), " +
        "$($skill.Property), $($skill.Mp), $(ConvertTo-CSharpDecimal $skill.Power1), $(ConvertTo-CSharpDecimal $skill.Power2), $(ConvertTo-CSharpString $skill.StatsJson)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("    public static IReadOnlyList<SkillBookTemplateSeed> SkillBooks { get; } =")
[void]$csharp.AppendLine("    [")
foreach ($book in $skillBooks) {
    [void]$csharp.AppendLine(
        "        new(" +
        "$($book.ItemId), $(ConvertTo-CSharpString $book.NameKey), $(ConvertTo-CSharpString $book.DisplayName), $($book.SkillId), " +
        "$(ConvertTo-CSharpString $book.BaseName), $(ConvertTo-CSharpNullableShort $book.SkillLevel), $(ConvertTo-CSharpShortArray $book.ClassIds), " +
        "$(ConvertTo-CSharpNullableInt $book.MinLevel), $(ConvertTo-CSharpNullableInt $book.MaxLevel), $(ConvertTo-CSharpNullableInt $book.PreviousSkillId), $(ConvertTo-CSharpString $book.StatsJson)),")
}
[void]$csharp.AppendLine("    ];")
[void]$csharp.AppendLine("}")
