$csharpChunkOwnershipMarker =
    "// <auto-generated skill-talent-seed chunk />"
$csharpGeneratedComment =
    "// Generated from Godswar Origin Skill.ini, Magic.ini, ItemBaseAttribute.xml, EquipName.dat, and SkillInfo.dat."
$csharpMaximumGeneratedBytes = 16000
$csharpMaximumGeneratedLines = 550

function New-CSharpChunkContent(
    [string]$collectionName,
    [string]$seedType,
    [int]$chunkIndex,
    [string[]]$entries
) {
    $methodName =
        "Create{0}Chunk{1:D3}" -f $collectionName, $chunkIndex
    $builder = [System.Text.StringBuilder]::new()
    [void]$builder.AppendLine($csharpChunkOwnershipMarker)
    [void]$builder.AppendLine($csharpGeneratedComment)
    [void]$builder.AppendLine("namespace Godswar.Server.State;")
    [void]$builder.AppendLine()
    [void]$builder.AppendLine(
        "internal static partial class SkillTalentSeeds")
    [void]$builder.AppendLine("{")
    [void]$builder.AppendLine(
        "    private static $seedType[] $methodName() =>")
    [void]$builder.AppendLine("    [")
    foreach ($entry in $entries) {
        [void]$builder.AppendLine($entry)
    }
    [void]$builder.AppendLine("    ];")
    [void]$builder.AppendLine("}")

    return [pscustomobject]@{
        CollectionName = $collectionName
        ChunkIndex = $chunkIndex
        MethodName = $methodName
        Content = $builder.ToString()
    }
}

function Get-CSharpGeneratedContentSize([string]$content) {
    return (
        [System.Text.Encoding]::UTF8.GetPreamble().Length +
        [System.Text.Encoding]::UTF8.GetByteCount($content)
    )
}

function Get-CSharpGeneratedContentLineCount([string]$content) {
    return ($content -split "\r\n|\n|\r").Count
}

function Test-CSharpGeneratedContentFits([string]$content) {
    return (
        (Get-CSharpGeneratedContentSize $content) -le
            $csharpMaximumGeneratedBytes -and
        (Get-CSharpGeneratedContentLineCount $content) -le
            $csharpMaximumGeneratedLines
    )
}

function Split-CSharpSeedEntries(
    [string]$collectionName,
    [string]$seedType,
    [string[]]$entries
) {
    $chunks = [System.Collections.Generic.List[object]]::new()
    $currentEntries = [System.Collections.Generic.List[string]]::new()
    $chunkIndex = 0

    foreach ($entry in $entries) {
        $candidateEntries = [string[]]@(
            $currentEntries.ToArray()
            $entry
        )
        $candidate = New-CSharpChunkContent `
            $collectionName `
            $seedType `
            $chunkIndex `
            $candidateEntries

        if (
            $currentEntries.Count -gt 0 -and
            -not (Test-CSharpGeneratedContentFits $candidate.Content)
        ) {
            $chunk = New-CSharpChunkContent `
                $collectionName `
                $seedType `
                $chunkIndex `
                $currentEntries.ToArray()
            [void]$chunks.Add($chunk)
            $chunkIndex++
            $currentEntries.Clear()
            [void]$currentEntries.Add($entry)

            $singleEntryChunk = New-CSharpChunkContent `
                $collectionName `
                $seedType `
                $chunkIndex `
                $currentEntries.ToArray()
            if (-not (
                Test-CSharpGeneratedContentFits $singleEntryChunk.Content
            )) {
                throw (
                    "Generated $collectionName entry cannot fit within " +
                    "$csharpMaximumGeneratedBytes bytes and " +
                    "$csharpMaximumGeneratedLines lines."
                )
            }

            continue
        }

        [void]$currentEntries.Add($entry)
    }

    if ($currentEntries.Count -gt 0) {
        $chunk = New-CSharpChunkContent `
            $collectionName `
            $seedType `
            $chunkIndex `
            $currentEntries.ToArray()
        [void]$chunks.Add($chunk)
    }

    return $chunks.ToArray()
}

$classEntries = [string[]]@(
    foreach ($class in $classes) {
        "        new($($class.Id), $(ConvertTo-CSharpString $class.Name), $(ConvertTo-CSharpString $class.DisplayName), $(ConvertTo-CSharpString $class.Source)),"
    }
)

$talentEffectEntries = [string[]]@(
    foreach ($effect in $talentEffects) {
        "        new($($effect.Id), $(ConvertTo-CSharpString $effect.Key), $(ConvertTo-CSharpString $effect.DisplayName), $($effect.Percent.ToString().ToLowerInvariant())),"
    }
)

$talentEntries = [string[]]@(
    foreach ($talent in $talents) {
        "        new(" +
        "$($talent.Id), $($talent.ClassId), $($talent.TreeOrder), " +
        "$(ConvertTo-CSharpString $talent.Name), $($talent.PrefixId), $($talent.RequiredPrefixRank), $($talent.RequiredTotalRank), $($talent.EquipRequest), " +
        "$(ConvertTo-CSharpString $talent.EffectType), $($talent.EffectId), $(ConvertTo-CSharpDecimal $talent.EffectValue), $($talent.IsPercent.ToString().ToLowerInvariant()), " +
        "$($talent.IconX), $($talent.IconY), $($talent.IconWidth), $($talent.IconHeight), $(ConvertTo-CSharpString $talent.StatsJson)),"
    }
)

$skillEntries = [string[]]@(
    foreach ($skill in $skills) {
        "        new(" +
        "$($skill.SkillId), $(ConvertTo-CSharpString $skill.DisplayName), $(ConvertTo-CSharpString $skill.BaseName), $(ConvertTo-CSharpNullableShort $skill.SkillLevel), " +
        "$(ConvertTo-CSharpShortArray $skill.ClassIds), $(ConvertTo-CSharpNullableInt $skill.PreviousSkillId), $(ConvertTo-CSharpNullableInt $skill.MinLevel), $(ConvertTo-CSharpNullableInt $skill.MaxLevel), " +
        "$(ConvertTo-CSharpString $skill.Description), $($skill.Target), $($skill.AffectObj), $(ConvertTo-CSharpDecimal $skill.Distance), $(ConvertTo-CSharpDecimal $skill.Range), " +
        "$($skill.Property), $($skill.Mp), $(ConvertTo-CSharpDecimal $skill.Power1), $(ConvertTo-CSharpDecimal $skill.Power2), " +
        "$(ConvertTo-CSharpDecimal $skill.IntonateTime), $(ConvertTo-CSharpDecimal $skill.CoolingTime), $(ConvertTo-CSharpString $skill.StatsJson)),"
    }
)

$skillBookEntries = [string[]]@(
    foreach ($book in $skillBooks) {
        "        new(" +
        "$($book.ItemId), $(ConvertTo-CSharpString $book.NameKey), $(ConvertTo-CSharpString $book.DisplayName), $($book.SkillId), " +
        "$(ConvertTo-CSharpString $book.BaseName), $(ConvertTo-CSharpNullableShort $book.SkillLevel), $(ConvertTo-CSharpShortArray $book.ClassIds), " +
        "$(ConvertTo-CSharpNullableInt $book.MinLevel), $(ConvertTo-CSharpNullableInt $book.MaxLevel), $(ConvertTo-CSharpNullableInt $book.PreviousSkillId), $(ConvertTo-CSharpString $book.StatsJson)),"
    }
)

$csharpCollections = @(
    [pscustomobject]@{
        Name = "Classes"
        SeedType = "ClassTemplateSeed"
        Entries = $classEntries
    },
    [pscustomobject]@{
        Name = "TalentEffects"
        SeedType = "TalentEffectTemplateSeed"
        Entries = $talentEffectEntries
    },
    [pscustomobject]@{
        Name = "Talents"
        SeedType = "TalentTemplateSeed"
        Entries = $talentEntries
    },
    [pscustomobject]@{
        Name = "Skills"
        SeedType = "SkillTemplateSeed"
        Entries = $skillEntries
    },
    [pscustomobject]@{
        Name = "SkillBooks"
        SeedType = "SkillBookTemplateSeed"
        Entries = $skillBookEntries
    }
)

$csharpChunksByCollection = [ordered]@{}
foreach ($collection in $csharpCollections) {
    $csharpChunksByCollection[$collection.Name] = @(
        Split-CSharpSeedEntries `
            $collection.Name `
            $collection.SeedType `
            $collection.Entries
    )
}

$csharp = [System.Text.StringBuilder]::new()
[void]$csharp.AppendLine("// <auto-generated />")
[void]$csharp.AppendLine($csharpGeneratedComment)
[void]$csharp.AppendLine("namespace Godswar.Server.State;")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct ClassTemplateSeed(short Id, string Name, string DisplayName, string Source);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct TalentEffectTemplateSeed(short Id, string Key, string DisplayName, bool Percent);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct TalentTemplateSeed(")
[void]$csharp.AppendLine("    int Id,")
[void]$csharp.AppendLine("    short ClassId,")
[void]$csharp.AppendLine("    short TreeOrder,")
[void]$csharp.AppendLine("    string Name,")
[void]$csharp.AppendLine("    int PrefixId,")
[void]$csharp.AppendLine("    int RequiredPrefixRank,")
[void]$csharp.AppendLine("    int RequiredTotalRank,")
[void]$csharp.AppendLine("    int EquipRequest,")
[void]$csharp.AppendLine("    string EffectType,")
[void]$csharp.AppendLine("    short EffectId,")
[void]$csharp.AppendLine("    decimal EffectValue,")
[void]$csharp.AppendLine("    bool IsPercent,")
[void]$csharp.AppendLine("    int IconX,")
[void]$csharp.AppendLine("    int IconY,")
[void]$csharp.AppendLine("    int IconWidth,")
[void]$csharp.AppendLine("    int IconHeight,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct SkillTemplateSeed(")
[void]$csharp.AppendLine("    int SkillId,")
[void]$csharp.AppendLine("    string DisplayName,")
[void]$csharp.AppendLine("    string BaseName,")
[void]$csharp.AppendLine("    short? SkillLevel,")
[void]$csharp.AppendLine("    short[] ClassIds,")
[void]$csharp.AppendLine("    int? PreviousSkillId,")
[void]$csharp.AppendLine("    int? MinLevel,")
[void]$csharp.AppendLine("    int? MaxLevel,")
[void]$csharp.AppendLine("    string Description,")
[void]$csharp.AppendLine("    int Target,")
[void]$csharp.AppendLine("    int AffectObj,")
[void]$csharp.AppendLine("    decimal Distance,")
[void]$csharp.AppendLine("    decimal Range,")
[void]$csharp.AppendLine("    int Property,")
[void]$csharp.AppendLine("    int Mp,")
[void]$csharp.AppendLine("    decimal Power1,")
[void]$csharp.AppendLine("    decimal Power2,")
[void]$csharp.AppendLine("    decimal IntonateTime,")
[void]$csharp.AppendLine("    decimal CoolingTime,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal readonly record struct SkillBookTemplateSeed(")
[void]$csharp.AppendLine("    int ItemId,")
[void]$csharp.AppendLine("    string NameKey,")
[void]$csharp.AppendLine("    string DisplayName,")
[void]$csharp.AppendLine("    int SkillId,")
[void]$csharp.AppendLine("    string BaseName,")
[void]$csharp.AppendLine("    short? SkillLevel,")
[void]$csharp.AppendLine("    short[] ClassIds,")
[void]$csharp.AppendLine("    int? MinLevel,")
[void]$csharp.AppendLine("    int? MaxLevel,")
[void]$csharp.AppendLine("    int? PreviousSkillId,")
[void]$csharp.AppendLine("    string StatsJson);")
[void]$csharp.AppendLine()
[void]$csharp.AppendLine("internal static partial class SkillTalentSeeds")
[void]$csharp.AppendLine("{")
foreach ($collection in $csharpCollections) {
    [void]$csharp.AppendLine(
        "    public static IReadOnlyList<$($collection.SeedType)> $($collection.Name) { get; } =")
    [void]$csharp.AppendLine("    [")
    foreach ($chunk in $csharpChunksByCollection[$collection.Name]) {
        [void]$csharp.AppendLine(
            "        .. $($chunk.MethodName)(),")
    }
    [void]$csharp.AppendLine("    ];")
    [void]$csharp.AppendLine()
}
[void]$csharp.AppendLine("}")

$resolvedCSharpOutputPath =
    [System.IO.Path]::GetFullPath($CSharpOutputPath)
$csharpChunkOutputDirectory =
    [System.IO.Path]::GetDirectoryName($resolvedCSharpOutputPath)
$csharpOutputBaseName =
    [System.IO.Path]::GetFileNameWithoutExtension(
        $resolvedCSharpOutputPath)
$csharpChunkFileNamePattern =
    "^" +
    [System.Text.RegularExpressions.Regex]::Escape(
        $csharpOutputBaseName) +
    "\.(Classes|TalentEffects|Talents|Skills|SkillBooks)\.Chunk\d{3}\.cs$"

$csharpGeneratedFiles = [ordered]@{}
$csharpGeneratedFiles[$resolvedCSharpOutputPath] = $csharp.ToString()
foreach ($collection in $csharpCollections) {
    foreach ($chunk in $csharpChunksByCollection[$collection.Name]) {
        $chunkFileName =
            "{0}.{1}.Chunk{2:D3}.cs" -f `
                $csharpOutputBaseName, `
                $collection.Name, `
                $chunk.ChunkIndex
        $chunkPath = Join-Path `
            $csharpChunkOutputDirectory `
            $chunkFileName
        $csharpGeneratedFiles[
            [System.IO.Path]::GetFullPath($chunkPath)
        ] = $chunk.Content
    }
}

foreach ($generatedFile in $csharpGeneratedFiles.GetEnumerator()) {
    if (-not (
        Test-CSharpGeneratedContentFits $generatedFile.Value
    )) {
        throw (
            "Generated C# file '$($generatedFile.Key)' exceeds " +
            "$csharpMaximumGeneratedBytes bytes or " +
            "$csharpMaximumGeneratedLines lines."
        )
    }
}
